/** P6 closeout census lists. Sourced from tests/unit/schema/convex-schema.test.ts. */

export const CUSTOMER_REQUEST_EXPORT_TABLES = [
  'customerRequestRouteMandateIssues',
  'customerRequestRouteMandateHeads',
  'customerRequestRouteMandateCommands',
  'customerRequestRouteMandateRevocations',
  'customerRequestRouteMandateRevocationCommands',
  'customerRequestRouteStepReservations',
  'customerRequestRouteDataReservations',
  'customerRequestRouteStepAdmissionCommands',
  'customerRequestRouteRuns',
  'customerRequestRouteRunHeads',
  'customerRequestRouteRunCommands',
  'customerRequestRouteCancellationCommands',
  'customerRequestRouteProblemReports',
  'customerRequestRouteProblemUpdates',
  'customerRequestRouteStepAttempts',
  'customerRequestRouteDispatchOutbox',
  'customerRequestX402PaymentAttempts',
  'customerRequestV2Heads',
  'customerRequestV2Revisions',
  'customerRequestV2RoutePlanGenerations',
  'customerRequestV2RoutePlanHeads',
  'customerRequestV2Commands',
  'customerRequestV2RoutePlanGenerationCommands',
  'customerRequestV2ActionPreparations',
  'customerRequestV2PreparationCommands',
  'customerRequestV2PreparationDisclosureReviews',
  'customerRequestV2PreparationApprovalEvidence',
  'customerRequestV2PreparationAuthorityReservations',
  'customerRequestV2PreparationEgressConsumption',
  'customerRequestV2PreparationEgressCommands',
  'customerRequestV2PreparationEgressOperations',
  'customerRequestV2PreparationDisclosureAllocations',
  'customerRequestV2PreparationReconciliationObservations',
  'customerRequestV2PreparedActions',
  'customerRequestV2PreparedActionRecoveries',
  'customerRequestV2PreparedActionCommands',
  'customerRequestV2ApprovalGrants',
  'customerRequestV2ApprovalGrantCommands',
  'customerRequestV2ActionAttempts',
  'customerRequestV2ActionAuthorityBudgets',
  'customerRequestV2ApprovalGrantConsumptions',
  'customerRequestV2ActionAttemptIdempotencyClaims',
  'customerRequestV2ActionAttemptSpendReservations',
  'customerRequestV2ActionAttemptDataReservations',
  'customerRequestV2ProviderReleaseGrants',
  'customerRequestV2ActionDisclosureGrants',
  'customerRequestV2ActionAttemptReleases',
  'customerRequestV2ProviderOutcomes',
  'customerRequestV2ProviderRootRuns',
  'customerRequestV2ProviderLeafRuns',
  'customerRequestV2ProviderProtocolEvidence',
  'customerRequestV2ProviderReconciliationObservations',
  'customerRequestV2ActionAttemptResolutions',
  'customerRequestV2ProviderReconciliationCommands',
  'customerRequestV2ActionAttemptAdmissionCommands',
  'customerRequestRouteCancellationAttempts',
  'customerRequestRouteProblemBusinessReports',
  'customerRequestStandingRoutePolicyIssues',
  'customerRequestStandingRoutePolicyCommands',
  'customerRequestStandingRoutePolicyRevocations',
  'customerRequestStandingRoutePolicyRevocationCommands',
  'customerRequestStandingRouteAuthorityUses',
  'customerRequestStandingRouteAuthorityUseCommands',
  'customerRequestV2SubmissionShells',
] as const

export const ROUTING_KERNEL_EXPORT_TABLES = [
  'routingKernelAdmissionMeters',
  'routingKernelAdmissionLeases',
  'routingKernelAdmissionDecisions',
  'routingKernelProviderTelemetry',
  'routingKernelQuotes',
  'routingKernelIncidentScopeControls',
  'routingKernelIncidentFreezeOrders',
  'routingKernelIncidentResumeOrders',
  'routingKernelIncidentResumeApprovals',
  'routingKernelIncidentRefinementApprovals',
  'routingKernelIncidentRefinementFacts',
  'routingKernelIncidentRecoveryGrantApprovals',
  'routingKernelIncidentRecoveryGrants',
  'routingKernelIncidentRecoveryUses',
  'routingKernelIncidentEvidenceQuarantines',
  'routingKernelIncidentReconstructionCheckpoints',
  'routingKernelIncidentReconformanceFacts',
  'routingKernelIncidentCanaryRunFacts',
  'routingKernelIncidentDrainSweeps',
  'routingKernelIncidentDrainFacts',
  'routingKernelAgentGrants',
  'routingKernelBindingEvidenceSnapshots',
  'routingKernelBindings',
  'routingKernelQuoteGraphs',
  'routingKernelQuoteGraphSteps',
  'routingKernelAuthorizations',
  'routingKernelBudgetAuthorities',
  'routingKernelSpendReservations',
  'routingKernelDataAuthorizationBudgets',
  'routingKernelDataAllocations',
  'routingKernelDisclosureAttempts',
  'routingKernelProviderCancellations',
  'routingKernelExecutionClaims',
  'routingKernelStepReleases',
  'routingKernelRootRuns',
  'routingKernelLeafRuns',
  'routingKernelProtocolRecords',
  'routingKernelPreparationCandidateSets',
  'routingKernelPreparationCandidates',
  'routingKernelPreparationQuoteAttempts',
  'routingKernelPreparationQuoteAttemptFields',
  'routingKernelProviderOffers',
  'routingKernelProviderOfferExecutionFields',
  'routingKernelProviderOfferMaterialTerms',
] as const

export const WORK_TREE_EXPORT_TABLES = [
  'workTreeApprovals',
  'workTreeDecisionReceipts',
  'workTreeEvents',
  'workTreeRepeatPermissions',
  'workTreeRepeatUses',
  'workTrees',
] as const

export const STUDY_EXPORT_TABLES = [
  'studies',
  'studyEvents',
] as const

export const PROJECT_SPINE_EXPORT_TABLES = [
  'projectSpine',
  'projectSpineEvents',
  'projectSpineQuotes',
] as const

export const INQUIRY_EXPORT_TABLES = [
  'capabilityLaunchSupportRecords',
  'inquiryThreads',
  'inquiryCustomerAccessGrants',
  'inquiryMessages',
  'inquiryNotifications',
  'inquiryReadStates',
  'inquiryAbuseBuckets',
  'inquiryPrivacyTombstones',
  'governedSendReceipts',
  'governedSendIntegrityCommitments',
  'governedSendReceiptKeys',
  'governedSendErasureLineage',
] as const

export const P6_CLOSEOUT_EXPORT_TABLES = [
  ...CUSTOMER_REQUEST_EXPORT_TABLES,
  ...ROUTING_KERNEL_EXPORT_TABLES,
  ...WORK_TREE_EXPORT_TABLES,
  ...STUDY_EXPORT_TABLES,
  ...PROJECT_SPINE_EXPORT_TABLES,
  ...INQUIRY_EXPORT_TABLES,
] as const
