export function buildPublicAgentSkillMarkdown(options: { canonicalBaseUrl: string; routingBaseUrl?: string }): string {
  const base = trimTrailingSlash(options.canonicalBaseUrl)
  const routingBase = trimTrailingSlash(options.routingBaseUrl ?? options.canonicalBaseUrl)
  return [
    '# Agentic Economy — assistant setup',
    '',
    `Fetch this file from the site origin (\`GET ${base}/SKILL.md\`). It teaches the cold path`,
    'for assistants that discover AE without a human briefing.',
    '',
    '## What AE is',
    '',
    'Give AE a natural-language request. AE asks for decision-changing information, checks',
    'connected registered businesses, and returns supported options. When the customer explicitly',
    'states a price priority and the evidence is comparable, AE may explain a recommendation. It does not select,',
    'purchase, or book anything in this workflow.',
    '',
    '## Request sequence (do this in order)',
    '',
    `1. Read \`GET ${base}/llms.txt\` for the current public surface index.`,
    '2. Obtain an AE API key with `customer_requests:create` and send it as a Bearer token.',
    `3. \`POST ${base}/api/v1/requests\` with an idempotency key, opaque request reference, and natural-language request. Known facts are optional; no budget or full specification is required to start.`,
    '4. Follow `clarification.answerKind`: send natural-language answers to `/messages`; send only requested typed values to `/facts`.',
    '5. To prepare, POST `/api/v1/requests/:requestRef/options` with the current revision and a new idempotency key.',
    '6. If AE returns `needs_authorization`, show the disclosure review. Only after explicit customer approval, POST `/options` again with a new idempotency key and `authorityReference` set to the returned opaque `preparationRef`.',
    '7. Resume at any time with `GET /api/v1/requests/:requestRef` using the same API key.',
    '8. Inspect `options_ready.optionSet.ordering`: `recommended` is tied to the stated objective, reasons, tradeoffs, and commercial-influence evidence; `unranked` means AE found no defensible ordering. Never infer selection or commitment.',
    '',
    `Browse without a search query: \`GET ${base}/api/businesses\` (list) or`,
    `\`GET ${base}/api/businesses/search?q=\`.`,
    '',
    '## Refusal recovery',
    '',
    '- `401` means the API key is missing, invalid, expired, or revoked.',
    '- `403` means the key lacks `customer_requests:create`.',
    '- `preparing_options` means wait or resume the same Request; do not create a replacement.',
    '- `needs_authorization` means show the disclosure review and stop until the customer explicitly approves it; never invent or imply consent.',
    '- `needs_attention` means retry or revise according to `nextAction`.',
    '',
    '## Boundaries (hard)',
    '',
    'Business listings are supply facts, not routing or execution authority.',
    'Never choose provider tools directly when delegating the decision to AE.',
    '',
    '## Advanced routing',
    '',
    `Low-level signed routing remains described at \`${routingBase}/.well-known/ae-routing.json\`.`,
    '',
    '## Privacy',
    '',
    `\`${base}/privacy/remove-business\` for listing correction or removal requests.`,
    '',
  ].join('\n')
}

function trimTrailingSlash(value: string): string {
  return value.endsWith('/') ? value.slice(0, -1) : value
}
