export {
  CREDENTIAL_LIFECYCLES,
  CREDENTIAL_TYPES,
  CLERK_USER_PROVIDER_NAMESPACE,
  EXTERNAL_IDENTITY_BINDING_LIFECYCLES,
  KNOWN_EXTERNAL_PROVIDER_STATES,
  ExternalIdentityRegistry,
  ExternalIdentityRegistryError,
  credentialRef,
  clerkUserProviderIdentifier,
  externalIdentityBindingRef,
  externalProviderState,
  generateCredentialRef,
  generateExternalIdentityBindingRef,
} from './registry'
export type {
  AuthenticatedExternalIdentity,
  Credential,
  CredentialLifecycle,
  CredentialRef,
  CredentialType,
  ExternalIdentityBinding,
  ExternalIdentityBindingLifecycle,
  ExternalIdentityBindingRef,
  ExternalIdentityRegistryCommit,
  ExternalIdentityRegistryErrorCode,
  ExternalIdentityRegistryOptions,
  ExternalIdentityRegistryStore,
  ExternalIdentityRegistryTransaction,
  ExternalProviderState,
  KnownExternalProviderState,
  RevisionedExternalIdentityReplacement,
} from './registry'
export {
  credentialLifecycleValue,
  credentialTypeValue,
  credentialValue,
  externalIdentityBindingLifecycleValue,
  externalIdentityBindingValue,
  externalIdentityTables,
  externalProviderStateValue,
} from './convex-schema'
