import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { DEPLOYMENT_MANIFEST, SOURCE_WRITE_FAMILIES, fieldRules, knownNames } from '../../src/lib/deployment/manifest'

// DEPLOYMENT_MANIFEST.configuration is the public export from manifest.ts and covers
// requiredProduction / controlledPackage5 / conditional / optional / forbiddenProduction.
// `knownNames` and the per-name `fieldRules` (url/boolean/host-list/credential-ref kinds) are
// exported directly from manifest.ts and imported above. `convex/convex.config.ts` cannot be
// imported here: `defineApp` / `app.use(...)` construct real Convex component definitions that
// throw "This code only works in Convex runtime" outside a Convex deployment (confirmed
// empirically under tsx), so its `env: { ... }` block is read by source parsing instead.

export type FieldKindInfo = Readonly<{ name: string; kind: string }>
export type RequirementGroupInput = Readonly<{
  scope: string
  code: string
  names: readonly string[]
  mode: 'all' | 'one-of'
  trigger?: readonly string[]
}>

export type EnvExampleManifestInput = Readonly<{
  requiredProduction: readonly RequirementGroupInput[]
  controlledPackage5: readonly RequirementGroupInput[]
  conditional: readonly RequirementGroupInput[]
  optional: readonly string[]
  forbiddenProduction: readonly string[]
  knownNames: readonly string[]
  fieldKinds: readonly FieldKindInfo[]
}>

export type RenderEnvExampleInput = Readonly<{
  manifest: EnvExampleManifestInput
  convexEnvNames: readonly string[]
  unclassifiedNames?: readonly string[]
}>

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const CONVEX_CONFIG_PATH = path.join(REPO_ROOT, 'convex/convex.config.ts')
export const ENV_EXAMPLE_PATH = path.join(REPO_ROOT, '.env.example')

const HEADER =
  '# Generated by npm run env:example from src/lib/deployment/manifest.ts and convex/convex.config.ts. Do not edit by hand.'

function extractBalancedBlock(source: string, openIndex: number, openChar: string, closeChar: string): string {
  let depth = 0
  let endIndex = -1
  for (let index = openIndex; index < source.length; index += 1) {
    const character = source[index]
    if (character === openChar) depth += 1
    else if (character === closeChar) {
      depth -= 1
      if (depth === 0) {
        endIndex = index
        break
      }
    }
  }
  if (endIndex === -1) throw new Error(`render-env-example: unbalanced \`${openChar}${closeChar}\` block`)
  return source.slice(openIndex + 1, endIndex)
}

/** `defineApp` cannot run outside a Convex deployment: read by source parsing. See file-header note. */
export function parseConvexEnvNames(source: string): readonly string[] {
  const envMarker = source.indexOf('env: {')
  if (envMarker === -1) throw new Error('render-env-example: could not locate `env: {` block in convex.config.ts')
  const openBrace = source.indexOf('{', envMarker)
  const block = extractBalancedBlock(source, openBrace, '{', '}')
  return [...block.matchAll(/^\s*([A-Z0-9_]+):/gm)].map((match) => match[1]!)
}

// Derived per-family source-write names (`AE_SOURCE_WRITE_PREVIOUS_KEYS_*`,
// `AE_SOURCE_WRITE_DERIVED_KEY_ID_*`, `AE_SOURCE_WRITE_PREVIOUS_DERIVED_KEY_IDS_*`) are recognized
// by `isKnown()` in manifest.ts via a regex built from the exported `SOURCE_WRITE_FAMILIES`, not
// via a static name list. Rebuild the same names here from that export rather than treating them
// as unclassified.
function sourceWriteDerivedNames(): readonly string[] {
  return SOURCE_WRITE_FAMILIES.flatMap((family) => {
    const suffix = family.toUpperCase()
    return [
      `AE_SOURCE_WRITE_PREVIOUS_KEYS_${suffix}`,
      `AE_SOURCE_WRITE_DERIVED_KEY_ID_${suffix}`,
      `AE_SOURCE_WRITE_PREVIOUS_DERIVED_KEY_IDS_${suffix}`,
    ]
  })
}

export function loadManifestInput(): EnvExampleManifestInput {
  const { requiredProduction, controlledPackage5, conditional, optional, forbiddenProduction } =
    DEPLOYMENT_MANIFEST.configuration
  return {
    requiredProduction,
    controlledPackage5,
    conditional,
    optional,
    forbiddenProduction,
    knownNames: [...knownNames, ...sourceWriteDerivedNames()],
    fieldKinds: fieldRules.map((rule) => ({ name: rule.name, kind: rule.kind })),
  }
}

export function loadConvexEnvNames(): readonly string[] {
  const source = readFileSync(CONVEX_CONFIG_PATH, 'utf8')
  return parseConvexEnvNames(source)
}

function fieldKindComment(fieldKinds: readonly FieldKindInfo[], name: string): string | undefined {
  const rule = fieldKinds.find((entry) => entry.name === name)
  return rule === undefined ? undefined : `# type: ${rule.kind}`
}

function renderName(
  name: string,
  comments: readonly string[],
  convexEnvNameSet: ReadonlySet<string>,
): string {
  const allComments = convexEnvNameSet.has(name)
    ? [...comments, '# also required on the Convex deployment']
    : comments
  const commentLines = allComments.map((comment) => `${comment}\n`).join('')
  return `${commentLines}${name}=\n`
}

function renderGroupSubsection(
  title: string,
  groups: readonly RequirementGroupInput[],
  describeGroup: (group: RequirementGroupInput) => string,
  fieldKinds: readonly FieldKindInfo[],
  convexEnvNameSet: ReadonlySet<string>,
  usedNames: Set<string>,
): string {
  const lines: string[] = [`### ${title}\n`]
  for (const group of groups) {
    const description = describeGroup(group)
    for (const name of [...group.names].sort()) {
      if (usedNames.has(name)) continue
      usedNames.add(name)
      const kindComment = fieldKindComment(fieldKinds, name)
      const comments = kindComment === undefined ? [description] : [description, kindComment]
      lines.push(renderName(name, comments, convexEnvNameSet))
    }
  }
  return lines.join('')
}

function renderFlatSubsection(
  title: string,
  names: readonly string[],
  comments: (name: string) => readonly string[],
  convexEnvNameSet: ReadonlySet<string>,
  usedNames: Set<string>,
): string {
  const lines: string[] = [`### ${title}\n`]
  for (const name of [...new Set(names)].sort()) {
    if (usedNames.has(name)) continue
    usedNames.add(name)
    lines.push(renderName(name, comments(name), convexEnvNameSet))
  }
  return lines.join('')
}

export function renderEnvExample(input: RenderEnvExampleInput): string {
  const { manifest, convexEnvNames, unclassifiedNames = [] } = input
  const convexEnvNameSet = new Set(convexEnvNames)
  const usedNames = new Set<string>()
  const sections: string[] = [HEADER, '', '## Web server (Vercel / Vite process)', '']

  sections.push(
    renderGroupSubsection(
      'Required in production',
      manifest.requiredProduction,
      (group) =>
        group.mode === 'one-of'
          ? `# required in production (one of: ${[...group.names].sort().join(', ')}) -- ${group.scope}: ${group.code}`
          : `# required in production -- ${group.scope}: ${group.code}`,
      manifest.fieldKinds,
      convexEnvNameSet,
      usedNames,
    ),
  )
  sections.push('')
  sections.push(
    renderGroupSubsection(
      'Controlled Package 5',
      manifest.controlledPackage5,
      (group) => `# required when Package 5 controlled rollout is active -- ${group.scope}: ${group.code}`,
      manifest.fieldKinds,
      convexEnvNameSet,
      usedNames,
    ),
  )
  sections.push('')
  sections.push(
    renderGroupSubsection(
      'Conditional',
      manifest.conditional,
      (group) =>
        `# required if ${[...(group.trigger ?? group.names)].sort().join(' or ')} is set -- ${group.scope}: ${group.code}`,
      manifest.fieldKinds,
      convexEnvNameSet,
      usedNames,
    ),
  )
  sections.push('')

  const fieldKindOnlyNames = manifest.fieldKinds
    .map((rule) => rule.name)
    .filter((name) => !usedNames.has(name) && !manifest.optional.includes(name) && !manifest.knownNames.includes(name))
  sections.push(
    renderFlatSubsection(
      'Optional',
      [...manifest.optional, ...fieldKindOnlyNames],
      (name) => {
        const kindComment = fieldKindComment(manifest.fieldKinds, name)
        return kindComment === undefined ? [] : [kindComment]
      },
      convexEnvNameSet,
      usedNames,
    ),
  )
  sections.push('')
  sections.push(
    renderFlatSubsection(
      'Known but unused by validation',
      manifest.knownNames,
      (name) => {
        const kindComment = fieldKindComment(manifest.fieldKinds, name)
        return kindComment === undefined
          ? ['# known name; not enforced by validateDeploymentManifest']
          : ['# known name; not enforced by validateDeploymentManifest', kindComment]
      },
      convexEnvNameSet,
      usedNames,
    ),
  )
  sections.push('')

  sections.push('### Forbidden in production\n')
  for (const name of [...manifest.forbiddenProduction].sort()) {
    if (usedNames.has(name)) continue
    usedNames.add(name)
    sections.push(renderName(name, ['# development only; must be absent in production'], convexEnvNameSet))
  }
  sections.push('')

  sections.push('## Convex deployment (set with: npx convex env set NAME value)', '')
  for (const name of [...new Set(convexEnvNames)].sort()) {
    sections.push(renderName(name, ['# optional'], new Set()))
  }

  if (unclassifiedNames.length > 0) {
    sections.push('')
    sections.push(
      '## Unclassified (present in the previous .env.example, not in any schema -- declare in manifest.ts or delete)',
      '',
    )
    for (const name of [...new Set(unclassifiedNames)].sort()) {
      sections.push(renderName(name, [], new Set()))
    }
  }

  return `${sections.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}

function extractEnvNamesFromExisting(existingSource: string): readonly string[] {
  return [...existingSource.matchAll(/^([A-Z][A-Z0-9_]*)=/gm)].map((match) => match[1]!)
}

export function computeUnclassifiedNames(
  manifest: EnvExampleManifestInput,
  convexEnvNames: readonly string[],
  existingEnvExampleSource: string,
): readonly string[] {
  const known = new Set<string>([
    ...manifest.requiredProduction.flatMap((group) => group.names),
    ...manifest.controlledPackage5.flatMap((group) => group.names),
    ...manifest.conditional.flatMap((group) => group.names),
    ...manifest.optional,
    ...manifest.forbiddenProduction,
    ...manifest.knownNames,
    ...manifest.fieldKinds.map((rule) => rule.name),
    ...convexEnvNames,
  ])
  return extractEnvNamesFromExisting(existingEnvExampleSource).filter((name) => !known.has(name))
}

function unifiedDiff(expected: string, actual: string): string {
  const expectedLines = expected.split('\n')
  const actualLines = actual.split('\n')
  const max = Math.max(expectedLines.length, actualLines.length)
  const diffLines: string[] = []
  for (let index = 0; index < max; index += 1) {
    const expectedLine = expectedLines[index]
    const actualLine = actualLines[index]
    if (expectedLine === actualLine) continue
    if (actualLine !== undefined) diffLines.push(`-${actualLine}`)
    if (expectedLine !== undefined) diffLines.push(`+${expectedLine}`)
  }
  return diffLines.join('\n')
}

export function main(argv: readonly string[] = process.argv.slice(2)): void {
  const checkOnly = argv.includes('--check')
  const manifest = loadManifestInput()
  const convexEnvNames = loadConvexEnvNames()
  const existing = safeReadEnvExample()
  const unclassifiedNames = computeUnclassifiedNames(manifest, convexEnvNames, existing ?? '')
  const rendered = renderEnvExample({ manifest, convexEnvNames, unclassifiedNames })

  if (checkOnly) {
    if (existing === rendered) {
      process.stdout.write('.env.example matches the manifest render.\n')
      return
    }
    process.stderr.write('.env.example is out of date with src/lib/deployment/manifest.ts / convex/convex.config.ts.\n')
    process.stderr.write(`${unifiedDiff(rendered, existing ?? '')}\n`)
    process.exitCode = 1
    return
  }

  writeFileSync(ENV_EXAMPLE_PATH, rendered)
  process.stdout.write(`Wrote ${path.relative(REPO_ROOT, ENV_EXAMPLE_PATH)}\n`)
  if (unclassifiedNames.length > 0) {
    process.stdout.write(`Unclassified names (declare in manifest.ts or delete): ${unclassifiedNames.join(', ')}\n`)
  }
}

function safeReadEnvExample(): string | undefined {
  try {
    return readFileSync(ENV_EXAMPLE_PATH, 'utf8')
  } catch {
    return undefined
  }
}

const entrypoint = process.argv[1]
if (entrypoint !== undefined && import.meta.url === pathToFileURL(entrypoint).href) main()
