import type { DevSeedBusinessFixture } from './dev-seed-business-fixtures'

export const CLUSTER_A_FIXTURES: readonly DevSeedBusinessFixture[] = [
  {
    requestedSlug: 'open-meteo-forecast',
    businessName: 'Open-Meteo — weather forecast',
    category: 'External public weather',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public Open-Meteo weather API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://open-meteo.com/en/docs / 2026-08-05',
    offerings: [{
      name: 'Open-Meteo weather forecast',
      category: 'Weather forecast',
      summary: 'Returns public current, hourly, or daily weather forecasts for a latitude/longitude through the keyless Open-Meteo API.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to the Open-Meteo free non-commercial fair-use limits; not a commercial weather guarantee.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'open-meteo-geocoding',
    businessName: 'Open-Meteo — geocoding search',
    category: 'External public geocoding',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public Open-Meteo geocoding API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://open-meteo.com/en/docs/geocoding-api / 2026-08-05',
    offerings: [{
      name: 'Open-Meteo geocoding search',
      category: 'Geocoding',
      summary: 'Searches place names and returns matching coordinates and metadata through the keyless Open-Meteo geocoding API.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to the Open-Meteo free non-commercial fair-use limits.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'wikipedia-rest-summary',
    businessName: 'Wikipedia — REST page summary',
    category: 'External public encyclopedia',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public MediaWiki REST API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://www.mediawiki.org/wiki/API:REST_API / 2026-08-05',
    offerings: [{
      name: 'Wikipedia page summary',
      category: 'Encyclopedia summary',
      summary: 'Returns a plain-text summary and metadata for a Wikipedia page through the keyless MediaWiki REST summary endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS with permissive CORS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to Wikimedia fair-use and rate limits; content remains CC BY-SA licensed.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'thecatapi-image-search',
    businessName: 'TheCatAPI — random cat images',
    category: 'External public image API',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public TheCatAPI; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://docs.thecatapi.com/api-reference/images/images-search / 2026-08-05',
    offerings: [{
      name: 'Random cat image search',
      category: 'Image retrieval',
      summary: 'Returns random cat image URLs and dimensions through the keyless TheCatAPI image search endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS under a fair-use rate limit; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation under a fair-use rate limit. Higher limits require an optional API key that AE does not require or supply.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'coingecko-simple-price-keyless',
    businessName: 'CoinGecko — simple price',
    category: 'External public market data',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public CoinGecko simple/price endpoint; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://docs.coingecko.com/reference/simple-price / 2026-08-05',
    offerings: [{
      name: 'CoinGecko simple price',
      category: 'Cryptocurrency market data',
      summary: 'Returns current market prices for one or more crypto ids against requested fiat currencies through the keyless CoinGecko simple/price endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS with public rate limits; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Reference prices only; not investment advice or a tradable quote.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'ipify',
    businessName: 'ipify — public IP',
    category: 'External public network utility',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public ipify endpoint; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://geo.ipify.org/docs / 2026-08-05',
    offerings: [{
      name: 'Get public IP',
      category: 'Network utility',
      summary: 'Returns the caller public IPv4 address through the keyless ipify endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Returns the caller public IP only; free and unrestricted per ipify.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
] as const
