import type { DevSeedBusinessFixture } from './dev-seed-business-fixtures'

export const CLUSTER_A_FIXTURES: readonly DevSeedBusinessFixture[] = [
  {
    requestedSlug: 'open-meteo-forecast',
    businessName: 'Open-Meteo — weather forecast',
    category: 'External public weather',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public Open-Meteo weather API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://open-meteo.com/en/docs / 2026-08-05',
    offerings: [{
      name: 'Open-Meteo weather forecast',
      category: 'Weather forecast',
      summary: 'Returns public current, hourly, or daily weather forecasts for a latitude/longitude through the keyless Open-Meteo API.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to the Open-Meteo free non-commercial fair-use limits; not a commercial weather guarantee.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'open-meteo-geocoding',
    businessName: 'Open-Meteo — geocoding search',
    category: 'External public geocoding',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public Open-Meteo geocoding API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://open-meteo.com/en/docs/geocoding-api / 2026-08-05',
    offerings: [{
      name: 'Open-Meteo geocoding search',
      category: 'Geocoding',
      summary: 'Searches place names and returns matching coordinates and metadata through the keyless Open-Meteo geocoding API.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to the Open-Meteo free non-commercial fair-use limits.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'wikipedia-rest-summary',
    businessName: 'Wikipedia — REST page summary',
    category: 'External public encyclopedia',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public MediaWiki REST API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://www.mediawiki.org/wiki/API:REST_API / 2026-08-05',
    offerings: [{
      name: 'Wikipedia page summary',
      category: 'Encyclopedia summary',
      summary: 'Returns a plain-text summary and metadata for a Wikipedia page through the keyless MediaWiki REST summary endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS with permissive CORS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Subject to Wikimedia fair-use and rate limits; content remains CC BY-SA licensed.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'mockster-cat-images',
    businessName: 'Mockster — random cat images',
    category: 'External public image API',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public Mockster image API; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://mockster.dev/docs/api/images / 2026-08-14',
    offerings: [{
      name: 'Random cat image batch',
      category: 'Image retrieval',
      summary: 'Returns the requested number of random cat image URLs through Mockster’s keyless image endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. AE limits each batch to ten images; image links are supplied by LoremFlickr and retain upstream licensing and attribution requirements.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'coingecko-simple-price-keyless',
    businessName: 'CoinGecko — simple price',
    category: 'External public market data',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public CoinGecko simple/price endpoint; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://docs.coingecko.com/reference/simple-price / 2026-08-05',
    offerings: [{
      name: 'CoinGecko simple price',
      category: 'Cryptocurrency market data',
      summary: 'Returns current market prices for one or more crypto ids against requested fiat currencies through the keyless CoinGecko simple/price endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS with public rate limits; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Reference prices only; not investment advice or a tradable quote.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
  {
    requestedSlug: 'ipify',
    businessName: 'ipify — public IP',
    category: 'External public network utility',
    suburb: 'Online',
    stateTerritory: 'External',
    ownerMessage: 'AE-curated keyless external operation using the public ipify endpoint; not provider-owned or endorsed.',
    sourceLabel: 'publicly_observed / https://geo.ipify.org/docs / 2026-08-05',
    offerings: [{
      name: 'Get AE runtime public IP',
      category: 'Network utility',
      summary: 'Returns the AE runtime server egress IPv4 address observed by the keyless ipify endpoint.',
      serviceAreaSummary: 'Online',
      availabilitySummary: 'Public keyless HTTPS; AE-verifiable and active-compatible',
      accessPaths: [],
      firstRequestMode: 'inquiry_available',
      publicDisclosure: 'Keyless public external operation. Returns the AE runtime server egress public IP only; it does not identify the human user or their device.',
      noContactReason: 'Keyless self-serve operation; invoke the registered AE operation directly without contacting the provider.',
    }],
  },
] as const
