/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexHealthRouteImport } from './routes/admin.index-health'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminAuditEventsRouteImport } from './routes/admin.audit-events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexHealthRoute = AdminIndexHealthRouteImport.update({
  id: '/admin/index-health',
  path: '/admin/index-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditEventsRoute = AdminAuditEventsRouteImport.update({
  id: '/admin/audit-events',
  path: '/admin/audit-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/audit-events': typeof AdminAuditEventsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/index-health': typeof AdminIndexHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit-events': typeof AdminAuditEventsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/index-health': typeof AdminIndexHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/audit-events': typeof AdminAuditEventsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/index-health': typeof AdminIndexHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin/audit-events' | '/admin/claims' | '/admin/index-health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/audit-events' | '/admin/claims' | '/admin/index-health'
  id:
    | '__root__'
    | '/'
    | '/admin/audit-events'
    | '/admin/claims'
    | '/admin/index-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditEventsRoute: typeof AdminAuditEventsRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminIndexHealthRoute: typeof AdminIndexHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/index-health': {
      id: '/admin/index-health'
      path: '/admin/index-health'
      fullPath: '/admin/index-health'
      preLoaderRoute: typeof AdminIndexHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-events': {
      id: '/admin/audit-events'
      path: '/admin/audit-events'
      fullPath: '/admin/audit-events'
      preLoaderRoute: typeof AdminAuditEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditEventsRoute: AdminAuditEventsRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminIndexHealthRoute: AdminIndexHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
