/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RRouteImport } from './routes/r'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OperatorRouteImport } from './routes/_operator'
import { Route as SKILLDotmdRouteImport } from './routes/SKILL[.]md'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TThreadIdRouteImport } from './routes/t.$threadId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as RRequestIdRouteImport } from './routes/r.$requestId'
import { Route as QAnswerIdRouteImport } from './routes/q.$answerId'
import { Route as PrivacyRemoveBusinessRouteImport } from './routes/privacy.remove-business'
import { Route as IThreadIdRouteImport } from './routes/i.$threadId'
import { Route as ClaimSuccessRouteImport } from './routes/claim.success'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiBusinessesRouteImport } from './routes/api.businesses'
import { Route as ApiAnswerRouteImport } from './routes/api.answer'
import { Route as DotwellKnownHttpMessageSignaturesDirectoryRouteImport } from './routes/[.]well-known/http-message-signatures-directory'
import { Route as SlugUcpRouteImport } from './routes/$slug.ucp'
import { Route as SlugInquiryRouteImport } from './routes/$slug.inquiry'
import { Route as ApiStorefrontImportDraftRouteImport } from './routes/api.storefront.import-draft'
import { Route as ApiObservabilityFunnelRouteImport } from './routes/api.observability.funnel'
import { Route as ApiNotificationResendWebhookRouteImport } from './routes/api.notification.resend-webhook'
import { Route as ApiNotificationResendDispatchRouteImport } from './routes/api.notification.resend-dispatch'
import { Route as ApiNotificationNovuDispatchRouteImport } from './routes/api.notification.novu-dispatch'
import { Route as ApiDiscoverySchemaRouteImport } from './routes/api.discovery.schema'
import { Route as ApiDiscoveryFixturesRouteImport } from './routes/api.discovery.fixtures'
import { Route as ApiDiscoveryExamplesRouteImport } from './routes/api.discovery.examples'
import { Route as ApiChatModelsRouteImport } from './routes/api.chat.models'
import { Route as ApiBusinessesSearchRouteImport } from './routes/api.businesses.search'
import { Route as ApiBusinessesSlugRouteImport } from './routes/api.businesses.$slug'
import { Route as ApiBusinessActionsStripeWebhookRouteImport } from './routes/api.business-actions.stripe-webhook'
import { Route as ApiBillingWebhookRouteImport } from './routes/api.billing.webhook'
import { Route as ApiAnswerTurnRouteImport } from './routes/api.answer.turn'
import { Route as ApiAnswerThreadsRouteImport } from './routes/api.answer.threads'
import { Route as ApiAnswerFollowUpChipsRouteImport } from './routes/api.answer.follow-up-chips'
import { Route as ApiAnswerEvalStatusRouteImport } from './routes/api.answer.eval-status'
import { Route as ApiAgentToolsRouteImport } from './routes/api.agent.tools'
import { Route as OperatorOwnerStatusRouteImport } from './routes/_operator/owner.status'
import { Route as OperatorOwnerSettingsRouteImport } from './routes/_operator/owner.settings'
import { Route as OperatorOwnerInquiriesRouteImport } from './routes/_operator/owner.inquiries'
import { Route as OperatorOwnerBusinessActionsRouteImport } from './routes/_operator/owner.business-actions'
import { Route as OperatorOwnerBillingRouteImport } from './routes/_operator/owner.billing'
import { Route as OperatorOwnerActionsRouteImport } from './routes/_operator/owner.actions'
import { Route as OperatorDevelopersDiscoveryRouteImport } from './routes/_operator/developers.discovery'
import { Route as OperatorAdminRunsRouteImport } from './routes/_operator/admin.runs'
import { Route as OperatorAdminProtectedActionsRouteImport } from './routes/_operator/admin.protected-actions'
import { Route as OperatorAdminMonetizationRouteImport } from './routes/_operator/admin.monetization'
import { Route as OperatorAdminInquiriesRouteImport } from './routes/_operator/admin.inquiries'
import { Route as OperatorAdminIndexHealthRouteImport } from './routes/_operator/admin.index-health'
import { Route as OperatorAdminClaimsRouteImport } from './routes/_operator/admin.claims'
import { Route as OperatorAdminBusinessActionsRouteImport } from './routes/_operator/admin.business-actions'
import { Route as OperatorAdminAuditEventsRouteImport } from './routes/_operator/admin.audit-events'
import { Route as ApiAnswerThreadsThreadIdRouteImport } from './routes/api.answer.threads.$threadId'
import { Route as OperatorOwnerInquiriesThreadIdRouteImport } from './routes/_operator/owner.inquiries.$threadId'
import { Route as OperatorOwnerBusinessActionsRequestIdRouteImport } from './routes/_operator/owner.business-actions.$requestId'
import { Route as OperatorOwnerBillingRedirectingRouteImport } from './routes/_operator/owner.billing.redirecting'
import { Route as OperatorOwnerBillingActivateRouteImport } from './routes/_operator/owner.billing.activate'
import { Route as OperatorOwnerActionsProposalIdRouteImport } from './routes/_operator/owner.actions.$proposalId'
import { Route as OperatorAdminRunsTurnIdRouteImport } from './routes/_operator/admin.runs.$turnId'
import { Route as OperatorAdminProtectedActionsProposalIdRouteImport } from './routes/_operator/admin.protected-actions.$proposalId'
import { Route as OperatorAdminMonetizationOperationIdRouteImport } from './routes/_operator/admin.monetization.$operationId'
import { Route as OperatorAdminBusinessActionsRequestIdRouteImport } from './routes/_operator/admin.business-actions.$requestId'
import { Route as OperatorOwnerBusinessActionsRequestIdReceiptRouteImport } from './routes/_operator/owner.business-actions.$requestId.receipt'
import { Route as OperatorOwnerBillingReturnOperationIdRouteImport } from './routes/_operator/owner.billing.return.$operationId'
import { Route as OperatorOwnerBillingReceiptsReceiptIdRouteImport } from './routes/_operator/owner.billing.receipts.$receiptId'
import { Route as OperatorOwnerBillingCancelOperationIdRouteImport } from './routes/_operator/owner.billing.cancel.$operationId'
import { Route as OperatorOwnerActionsProposalIdReceiptRouteImport } from './routes/_operator/owner.actions.$proposalId.receipt'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => rootRouteImport,
} as any)
const SKILLDotmdRoute = SKILLDotmdRouteImport.update({
  id: '/SKILL.md',
  path: '/SKILL.md',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TThreadIdRoute = TThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RRequestIdRoute = RRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => RRoute,
} as any)
const QAnswerIdRoute = QAnswerIdRouteImport.update({
  id: '/q/$answerId',
  path: '/q/$answerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRemoveBusinessRoute = PrivacyRemoveBusinessRouteImport.update({
  id: '/remove-business',
  path: '/remove-business',
  getParentRoute: () => PrivacyRoute,
} as any)
const IThreadIdRoute = IThreadIdRouteImport.update({
  id: '/i/$threadId',
  path: '/i/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimSuccessRoute = ClaimSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ClaimRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesRoute = ApiBusinessesRouteImport.update({
  id: '/api/businesses',
  path: '/api/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswerRoute = ApiAnswerRouteImport.update({
  id: '/api/answer',
  path: '/api/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownHttpMessageSignaturesDirectoryRoute =
  DotwellKnownHttpMessageSignaturesDirectoryRouteImport.update({
    id: '/.well-known/http-message-signatures-directory',
    path: '/.well-known/http-message-signatures-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugUcpRoute = SlugUcpRouteImport.update({
  id: '/ucp',
  path: '/ucp',
  getParentRoute: () => SlugRoute,
} as any)
const SlugInquiryRoute = SlugInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => SlugRoute,
} as any)
const ApiStorefrontImportDraftRoute =
  ApiStorefrontImportDraftRouteImport.update({
    id: '/api/storefront/import-draft',
    path: '/api/storefront/import-draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObservabilityFunnelRoute = ApiObservabilityFunnelRouteImport.update({
  id: '/api/observability/funnel',
  path: '/api/observability/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationResendWebhookRoute =
  ApiNotificationResendWebhookRouteImport.update({
    id: '/api/notification/resend-webhook',
    path: '/api/notification/resend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationResendDispatchRoute =
  ApiNotificationResendDispatchRouteImport.update({
    id: '/api/notification/resend-dispatch',
    path: '/api/notification/resend-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationNovuDispatchRoute =
  ApiNotificationNovuDispatchRouteImport.update({
    id: '/api/notification/novu-dispatch',
    path: '/api/notification/novu-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoverySchemaRoute = ApiDiscoverySchemaRouteImport.update({
  id: '/api/discovery/schema',
  path: '/api/discovery/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryFixturesRoute = ApiDiscoveryFixturesRouteImport.update({
  id: '/api/discovery/fixtures',
  path: '/api/discovery/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryExamplesRoute = ApiDiscoveryExamplesRouteImport.update({
  id: '/api/discovery/examples',
  path: '/api/discovery/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatModelsRoute = ApiChatModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiBusinessesSearchRoute = ApiBusinessesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiBusinessesRoute,
} as any)
const ApiBusinessesSlugRoute = ApiBusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBusinessesRoute,
} as any)
const ApiBusinessActionsStripeWebhookRoute =
  ApiBusinessActionsStripeWebhookRouteImport.update({
    id: '/api/business-actions/stripe-webhook',
    path: '/api/business-actions/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswerTurnRoute = ApiAnswerTurnRouteImport.update({
  id: '/turn',
  path: '/turn',
  getParentRoute: () => ApiAnswerRoute,
} as any)
const ApiAnswerThreadsRoute = ApiAnswerThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => ApiAnswerRoute,
} as any)
const ApiAnswerFollowUpChipsRoute = ApiAnswerFollowUpChipsRouteImport.update({
  id: '/follow-up-chips',
  path: '/follow-up-chips',
  getParentRoute: () => ApiAnswerRoute,
} as any)
const ApiAnswerEvalStatusRoute = ApiAnswerEvalStatusRouteImport.update({
  id: '/eval-status',
  path: '/eval-status',
  getParentRoute: () => ApiAnswerRoute,
} as any)
const ApiAgentToolsRoute = ApiAgentToolsRouteImport.update({
  id: '/api/agent/tools',
  path: '/api/agent/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorOwnerStatusRoute = OperatorOwnerStatusRouteImport.update({
  id: '/owner/status',
  path: '/owner/status',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerSettingsRoute = OperatorOwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerInquiriesRoute = OperatorOwnerInquiriesRouteImport.update({
  id: '/owner/inquiries',
  path: '/owner/inquiries',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerBusinessActionsRoute =
  OperatorOwnerBusinessActionsRouteImport.update({
    id: '/owner/business-actions',
    path: '/owner/business-actions',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorOwnerBillingRoute = OperatorOwnerBillingRouteImport.update({
  id: '/owner/billing',
  path: '/owner/billing',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerActionsRoute = OperatorOwnerActionsRouteImport.update({
  id: '/owner/actions',
  path: '/owner/actions',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorDevelopersDiscoveryRoute =
  OperatorDevelopersDiscoveryRouteImport.update({
    id: '/developers/discovery',
    path: '/developers/discovery',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminRunsRoute = OperatorAdminRunsRouteImport.update({
  id: '/admin/runs',
  path: '/admin/runs',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAdminProtectedActionsRoute =
  OperatorAdminProtectedActionsRouteImport.update({
    id: '/admin/protected-actions',
    path: '/admin/protected-actions',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminMonetizationRoute =
  OperatorAdminMonetizationRouteImport.update({
    id: '/admin/monetization',
    path: '/admin/monetization',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminInquiriesRoute = OperatorAdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAdminIndexHealthRoute =
  OperatorAdminIndexHealthRouteImport.update({
    id: '/admin/index-health',
    path: '/admin/index-health',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminClaimsRoute = OperatorAdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAdminBusinessActionsRoute =
  OperatorAdminBusinessActionsRouteImport.update({
    id: '/admin/business-actions',
    path: '/admin/business-actions',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminAuditEventsRoute =
  OperatorAdminAuditEventsRouteImport.update({
    id: '/admin/audit-events',
    path: '/admin/audit-events',
    getParentRoute: () => OperatorRoute,
  } as any)
const ApiAnswerThreadsThreadIdRoute =
  ApiAnswerThreadsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ApiAnswerThreadsRoute,
  } as any)
const OperatorOwnerInquiriesThreadIdRoute =
  OperatorOwnerInquiriesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => OperatorOwnerInquiriesRoute,
  } as any)
const OperatorOwnerBusinessActionsRequestIdRoute =
  OperatorOwnerBusinessActionsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => OperatorOwnerBusinessActionsRoute,
  } as any)
const OperatorOwnerBillingRedirectingRoute =
  OperatorOwnerBillingRedirectingRouteImport.update({
    id: '/redirecting',
    path: '/redirecting',
    getParentRoute: () => OperatorOwnerBillingRoute,
  } as any)
const OperatorOwnerBillingActivateRoute =
  OperatorOwnerBillingActivateRouteImport.update({
    id: '/activate',
    path: '/activate',
    getParentRoute: () => OperatorOwnerBillingRoute,
  } as any)
const OperatorOwnerActionsProposalIdRoute =
  OperatorOwnerActionsProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => OperatorOwnerActionsRoute,
  } as any)
const OperatorAdminRunsTurnIdRoute = OperatorAdminRunsTurnIdRouteImport.update({
  id: '/$turnId',
  path: '/$turnId',
  getParentRoute: () => OperatorAdminRunsRoute,
} as any)
const OperatorAdminProtectedActionsProposalIdRoute =
  OperatorAdminProtectedActionsProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => OperatorAdminProtectedActionsRoute,
  } as any)
const OperatorAdminMonetizationOperationIdRoute =
  OperatorAdminMonetizationOperationIdRouteImport.update({
    id: '/$operationId',
    path: '/$operationId',
    getParentRoute: () => OperatorAdminMonetizationRoute,
  } as any)
const OperatorAdminBusinessActionsRequestIdRoute =
  OperatorAdminBusinessActionsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => OperatorAdminBusinessActionsRoute,
  } as any)
const OperatorOwnerBusinessActionsRequestIdReceiptRoute =
  OperatorOwnerBusinessActionsRequestIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => OperatorOwnerBusinessActionsRequestIdRoute,
  } as any)
const OperatorOwnerBillingReturnOperationIdRoute =
  OperatorOwnerBillingReturnOperationIdRouteImport.update({
    id: '/return/$operationId',
    path: '/return/$operationId',
    getParentRoute: () => OperatorOwnerBillingRoute,
  } as any)
const OperatorOwnerBillingReceiptsReceiptIdRoute =
  OperatorOwnerBillingReceiptsReceiptIdRouteImport.update({
    id: '/receipts/$receiptId',
    path: '/receipts/$receiptId',
    getParentRoute: () => OperatorOwnerBillingRoute,
  } as any)
const OperatorOwnerBillingCancelOperationIdRoute =
  OperatorOwnerBillingCancelOperationIdRouteImport.update({
    id: '/cancel/$operationId',
    path: '/cancel/$operationId',
    getParentRoute: () => OperatorOwnerBillingRoute,
  } as any)
const OperatorOwnerActionsProposalIdReceiptRoute =
  OperatorOwnerActionsProposalIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => OperatorOwnerActionsProposalIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRouteWithChildren
  '/help': typeof HelpRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/r': typeof RRouteWithChildren
  '/registry': typeof RegistryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/inquiry': typeof SlugInquiryRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/api/answer': typeof ApiAnswerRouteWithChildren
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/claim/success': typeof ClaimSuccessRoute
  '/i/$threadId': typeof IThreadIdRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/q/$answerId': typeof QAnswerIdRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/admin/business-actions': typeof OperatorAdminBusinessActionsRouteWithChildren
  '/admin/claims': typeof OperatorAdminClaimsRoute
  '/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/admin/inquiries': typeof OperatorAdminInquiriesRoute
  '/admin/monetization': typeof OperatorAdminMonetizationRouteWithChildren
  '/admin/protected-actions': typeof OperatorAdminProtectedActionsRouteWithChildren
  '/admin/runs': typeof OperatorAdminRunsRouteWithChildren
  '/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/owner/actions': typeof OperatorOwnerActionsRouteWithChildren
  '/owner/billing': typeof OperatorOwnerBillingRouteWithChildren
  '/owner/business-actions': typeof OperatorOwnerBusinessActionsRouteWithChildren
  '/owner/inquiries': typeof OperatorOwnerInquiriesRouteWithChildren
  '/owner/settings': typeof OperatorOwnerSettingsRoute
  '/owner/status': typeof OperatorOwnerStatusRoute
  '/api/agent/tools': typeof ApiAgentToolsRoute
  '/api/answer/eval-status': typeof ApiAnswerEvalStatusRoute
  '/api/answer/follow-up-chips': typeof ApiAnswerFollowUpChipsRoute
  '/api/answer/threads': typeof ApiAnswerThreadsRouteWithChildren
  '/api/answer/turn': typeof ApiAnswerTurnRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/business-actions/stripe-webhook': typeof ApiBusinessActionsStripeWebhookRoute
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/fixtures': typeof ApiDiscoveryFixturesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/notification/novu-dispatch': typeof ApiNotificationNovuDispatchRoute
  '/api/notification/resend-dispatch': typeof ApiNotificationResendDispatchRoute
  '/api/notification/resend-webhook': typeof ApiNotificationResendWebhookRoute
  '/api/observability/funnel': typeof ApiObservabilityFunnelRoute
  '/api/storefront/import-draft': typeof ApiStorefrontImportDraftRoute
  '/admin/business-actions/$requestId': typeof OperatorAdminBusinessActionsRequestIdRoute
  '/admin/monetization/$operationId': typeof OperatorAdminMonetizationOperationIdRoute
  '/admin/protected-actions/$proposalId': typeof OperatorAdminProtectedActionsProposalIdRoute
  '/admin/runs/$turnId': typeof OperatorAdminRunsTurnIdRoute
  '/owner/actions/$proposalId': typeof OperatorOwnerActionsProposalIdRouteWithChildren
  '/owner/billing/activate': typeof OperatorOwnerBillingActivateRoute
  '/owner/billing/redirecting': typeof OperatorOwnerBillingRedirectingRoute
  '/owner/business-actions/$requestId': typeof OperatorOwnerBusinessActionsRequestIdRouteWithChildren
  '/owner/inquiries/$threadId': typeof OperatorOwnerInquiriesThreadIdRoute
  '/api/answer/threads/$threadId': typeof ApiAnswerThreadsThreadIdRoute
  '/owner/actions/$proposalId/receipt': typeof OperatorOwnerActionsProposalIdReceiptRoute
  '/owner/billing/cancel/$operationId': typeof OperatorOwnerBillingCancelOperationIdRoute
  '/owner/billing/receipts/$receiptId': typeof OperatorOwnerBillingReceiptsReceiptIdRoute
  '/owner/billing/return/$operationId': typeof OperatorOwnerBillingReturnOperationIdRoute
  '/owner/business-actions/$requestId/receipt': typeof OperatorOwnerBusinessActionsRequestIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRouteWithChildren
  '/help': typeof HelpRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/r': typeof RRouteWithChildren
  '/registry': typeof RegistryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/inquiry': typeof SlugInquiryRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/api/answer': typeof ApiAnswerRouteWithChildren
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/claim/success': typeof ClaimSuccessRoute
  '/i/$threadId': typeof IThreadIdRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/q/$answerId': typeof QAnswerIdRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/admin/business-actions': typeof OperatorAdminBusinessActionsRouteWithChildren
  '/admin/claims': typeof OperatorAdminClaimsRoute
  '/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/admin/inquiries': typeof OperatorAdminInquiriesRoute
  '/admin/monetization': typeof OperatorAdminMonetizationRouteWithChildren
  '/admin/protected-actions': typeof OperatorAdminProtectedActionsRouteWithChildren
  '/admin/runs': typeof OperatorAdminRunsRouteWithChildren
  '/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/owner/actions': typeof OperatorOwnerActionsRouteWithChildren
  '/owner/billing': typeof OperatorOwnerBillingRouteWithChildren
  '/owner/business-actions': typeof OperatorOwnerBusinessActionsRouteWithChildren
  '/owner/inquiries': typeof OperatorOwnerInquiriesRouteWithChildren
  '/owner/settings': typeof OperatorOwnerSettingsRoute
  '/owner/status': typeof OperatorOwnerStatusRoute
  '/api/agent/tools': typeof ApiAgentToolsRoute
  '/api/answer/eval-status': typeof ApiAnswerEvalStatusRoute
  '/api/answer/follow-up-chips': typeof ApiAnswerFollowUpChipsRoute
  '/api/answer/threads': typeof ApiAnswerThreadsRouteWithChildren
  '/api/answer/turn': typeof ApiAnswerTurnRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/business-actions/stripe-webhook': typeof ApiBusinessActionsStripeWebhookRoute
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/fixtures': typeof ApiDiscoveryFixturesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/notification/novu-dispatch': typeof ApiNotificationNovuDispatchRoute
  '/api/notification/resend-dispatch': typeof ApiNotificationResendDispatchRoute
  '/api/notification/resend-webhook': typeof ApiNotificationResendWebhookRoute
  '/api/observability/funnel': typeof ApiObservabilityFunnelRoute
  '/api/storefront/import-draft': typeof ApiStorefrontImportDraftRoute
  '/admin/business-actions/$requestId': typeof OperatorAdminBusinessActionsRequestIdRoute
  '/admin/monetization/$operationId': typeof OperatorAdminMonetizationOperationIdRoute
  '/admin/protected-actions/$proposalId': typeof OperatorAdminProtectedActionsProposalIdRoute
  '/admin/runs/$turnId': typeof OperatorAdminRunsTurnIdRoute
  '/owner/actions/$proposalId': typeof OperatorOwnerActionsProposalIdRouteWithChildren
  '/owner/billing/activate': typeof OperatorOwnerBillingActivateRoute
  '/owner/billing/redirecting': typeof OperatorOwnerBillingRedirectingRoute
  '/owner/business-actions/$requestId': typeof OperatorOwnerBusinessActionsRequestIdRouteWithChildren
  '/owner/inquiries/$threadId': typeof OperatorOwnerInquiriesThreadIdRoute
  '/api/answer/threads/$threadId': typeof ApiAnswerThreadsThreadIdRoute
  '/owner/actions/$proposalId/receipt': typeof OperatorOwnerActionsProposalIdReceiptRoute
  '/owner/billing/cancel/$operationId': typeof OperatorOwnerBillingCancelOperationIdRoute
  '/owner/billing/receipts/$receiptId': typeof OperatorOwnerBillingReceiptsReceiptIdRoute
  '/owner/billing/return/$operationId': typeof OperatorOwnerBillingReturnOperationIdRoute
  '/owner/business-actions/$requestId/receipt': typeof OperatorOwnerBusinessActionsRequestIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/_operator': typeof OperatorRouteWithChildren
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRouteWithChildren
  '/help': typeof HelpRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRouteWithChildren
  '/r': typeof RRouteWithChildren
  '/registry': typeof RegistryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/inquiry': typeof SlugInquiryRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/api/answer': typeof ApiAnswerRouteWithChildren
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/chat': typeof ApiChatRouteWithChildren
  '/claim/success': typeof ClaimSuccessRoute
  '/i/$threadId': typeof IThreadIdRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/q/$answerId': typeof QAnswerIdRoute
  '/r/$requestId': typeof RRequestIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/_operator/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/_operator/admin/business-actions': typeof OperatorAdminBusinessActionsRouteWithChildren
  '/_operator/admin/claims': typeof OperatorAdminClaimsRoute
  '/_operator/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/_operator/admin/inquiries': typeof OperatorAdminInquiriesRoute
  '/_operator/admin/monetization': typeof OperatorAdminMonetizationRouteWithChildren
  '/_operator/admin/protected-actions': typeof OperatorAdminProtectedActionsRouteWithChildren
  '/_operator/admin/runs': typeof OperatorAdminRunsRouteWithChildren
  '/_operator/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/_operator/owner/actions': typeof OperatorOwnerActionsRouteWithChildren
  '/_operator/owner/billing': typeof OperatorOwnerBillingRouteWithChildren
  '/_operator/owner/business-actions': typeof OperatorOwnerBusinessActionsRouteWithChildren
  '/_operator/owner/inquiries': typeof OperatorOwnerInquiriesRouteWithChildren
  '/_operator/owner/settings': typeof OperatorOwnerSettingsRoute
  '/_operator/owner/status': typeof OperatorOwnerStatusRoute
  '/api/agent/tools': typeof ApiAgentToolsRoute
  '/api/answer/eval-status': typeof ApiAnswerEvalStatusRoute
  '/api/answer/follow-up-chips': typeof ApiAnswerFollowUpChipsRoute
  '/api/answer/threads': typeof ApiAnswerThreadsRouteWithChildren
  '/api/answer/turn': typeof ApiAnswerTurnRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/business-actions/stripe-webhook': typeof ApiBusinessActionsStripeWebhookRoute
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/models': typeof ApiChatModelsRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/fixtures': typeof ApiDiscoveryFixturesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/notification/novu-dispatch': typeof ApiNotificationNovuDispatchRoute
  '/api/notification/resend-dispatch': typeof ApiNotificationResendDispatchRoute
  '/api/notification/resend-webhook': typeof ApiNotificationResendWebhookRoute
  '/api/observability/funnel': typeof ApiObservabilityFunnelRoute
  '/api/storefront/import-draft': typeof ApiStorefrontImportDraftRoute
  '/_operator/admin/business-actions/$requestId': typeof OperatorAdminBusinessActionsRequestIdRoute
  '/_operator/admin/monetization/$operationId': typeof OperatorAdminMonetizationOperationIdRoute
  '/_operator/admin/protected-actions/$proposalId': typeof OperatorAdminProtectedActionsProposalIdRoute
  '/_operator/admin/runs/$turnId': typeof OperatorAdminRunsTurnIdRoute
  '/_operator/owner/actions/$proposalId': typeof OperatorOwnerActionsProposalIdRouteWithChildren
  '/_operator/owner/billing/activate': typeof OperatorOwnerBillingActivateRoute
  '/_operator/owner/billing/redirecting': typeof OperatorOwnerBillingRedirectingRoute
  '/_operator/owner/business-actions/$requestId': typeof OperatorOwnerBusinessActionsRequestIdRouteWithChildren
  '/_operator/owner/inquiries/$threadId': typeof OperatorOwnerInquiriesThreadIdRoute
  '/api/answer/threads/$threadId': typeof ApiAnswerThreadsThreadIdRoute
  '/_operator/owner/actions/$proposalId/receipt': typeof OperatorOwnerActionsProposalIdReceiptRoute
  '/_operator/owner/billing/cancel/$operationId': typeof OperatorOwnerBillingCancelOperationIdRoute
  '/_operator/owner/billing/receipts/$receiptId': typeof OperatorOwnerBillingReceiptsReceiptIdRoute
  '/_operator/owner/billing/return/$operationId': typeof OperatorOwnerBillingReturnOperationIdRoute
  '/_operator/owner/business-actions/$requestId/receipt': typeof OperatorOwnerBusinessActionsRequestIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/about'
    | '/claim'
    | '/help'
    | '/llms.txt'
    | '/privacy'
    | '/r'
    | '/registry'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/inquiry'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/api/answer'
    | '/api/businesses'
    | '/api/chat'
    | '/claim/success'
    | '/i/$threadId'
    | '/privacy/remove-business'
    | '/q/$answerId'
    | '/r/$requestId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/admin/audit-events'
    | '/admin/business-actions'
    | '/admin/claims'
    | '/admin/index-health'
    | '/admin/inquiries'
    | '/admin/monetization'
    | '/admin/protected-actions'
    | '/admin/runs'
    | '/developers/discovery'
    | '/owner/actions'
    | '/owner/billing'
    | '/owner/business-actions'
    | '/owner/inquiries'
    | '/owner/settings'
    | '/owner/status'
    | '/api/agent/tools'
    | '/api/answer/eval-status'
    | '/api/answer/follow-up-chips'
    | '/api/answer/threads'
    | '/api/answer/turn'
    | '/api/billing/webhook'
    | '/api/business-actions/stripe-webhook'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/models'
    | '/api/discovery/examples'
    | '/api/discovery/fixtures'
    | '/api/discovery/schema'
    | '/api/notification/novu-dispatch'
    | '/api/notification/resend-dispatch'
    | '/api/notification/resend-webhook'
    | '/api/observability/funnel'
    | '/api/storefront/import-draft'
    | '/admin/business-actions/$requestId'
    | '/admin/monetization/$operationId'
    | '/admin/protected-actions/$proposalId'
    | '/admin/runs/$turnId'
    | '/owner/actions/$proposalId'
    | '/owner/billing/activate'
    | '/owner/billing/redirecting'
    | '/owner/business-actions/$requestId'
    | '/owner/inquiries/$threadId'
    | '/api/answer/threads/$threadId'
    | '/owner/actions/$proposalId/receipt'
    | '/owner/billing/cancel/$operationId'
    | '/owner/billing/receipts/$receiptId'
    | '/owner/billing/return/$operationId'
    | '/owner/business-actions/$requestId/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/about'
    | '/claim'
    | '/help'
    | '/llms.txt'
    | '/privacy'
    | '/r'
    | '/registry'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/inquiry'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/api/answer'
    | '/api/businesses'
    | '/api/chat'
    | '/claim/success'
    | '/i/$threadId'
    | '/privacy/remove-business'
    | '/q/$answerId'
    | '/r/$requestId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/admin/audit-events'
    | '/admin/business-actions'
    | '/admin/claims'
    | '/admin/index-health'
    | '/admin/inquiries'
    | '/admin/monetization'
    | '/admin/protected-actions'
    | '/admin/runs'
    | '/developers/discovery'
    | '/owner/actions'
    | '/owner/billing'
    | '/owner/business-actions'
    | '/owner/inquiries'
    | '/owner/settings'
    | '/owner/status'
    | '/api/agent/tools'
    | '/api/answer/eval-status'
    | '/api/answer/follow-up-chips'
    | '/api/answer/threads'
    | '/api/answer/turn'
    | '/api/billing/webhook'
    | '/api/business-actions/stripe-webhook'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/models'
    | '/api/discovery/examples'
    | '/api/discovery/fixtures'
    | '/api/discovery/schema'
    | '/api/notification/novu-dispatch'
    | '/api/notification/resend-dispatch'
    | '/api/notification/resend-webhook'
    | '/api/observability/funnel'
    | '/api/storefront/import-draft'
    | '/admin/business-actions/$requestId'
    | '/admin/monetization/$operationId'
    | '/admin/protected-actions/$proposalId'
    | '/admin/runs/$turnId'
    | '/owner/actions/$proposalId'
    | '/owner/billing/activate'
    | '/owner/billing/redirecting'
    | '/owner/business-actions/$requestId'
    | '/owner/inquiries/$threadId'
    | '/api/answer/threads/$threadId'
    | '/owner/actions/$proposalId/receipt'
    | '/owner/billing/cancel/$operationId'
    | '/owner/billing/receipts/$receiptId'
    | '/owner/billing/return/$operationId'
    | '/owner/business-actions/$requestId/receipt'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/_operator'
    | '/about'
    | '/claim'
    | '/help'
    | '/llms.txt'
    | '/privacy'
    | '/r'
    | '/registry'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/inquiry'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/api/answer'
    | '/api/businesses'
    | '/api/chat'
    | '/claim/success'
    | '/i/$threadId'
    | '/privacy/remove-business'
    | '/q/$answerId'
    | '/r/$requestId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/_operator/admin/audit-events'
    | '/_operator/admin/business-actions'
    | '/_operator/admin/claims'
    | '/_operator/admin/index-health'
    | '/_operator/admin/inquiries'
    | '/_operator/admin/monetization'
    | '/_operator/admin/protected-actions'
    | '/_operator/admin/runs'
    | '/_operator/developers/discovery'
    | '/_operator/owner/actions'
    | '/_operator/owner/billing'
    | '/_operator/owner/business-actions'
    | '/_operator/owner/inquiries'
    | '/_operator/owner/settings'
    | '/_operator/owner/status'
    | '/api/agent/tools'
    | '/api/answer/eval-status'
    | '/api/answer/follow-up-chips'
    | '/api/answer/threads'
    | '/api/answer/turn'
    | '/api/billing/webhook'
    | '/api/business-actions/stripe-webhook'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/models'
    | '/api/discovery/examples'
    | '/api/discovery/fixtures'
    | '/api/discovery/schema'
    | '/api/notification/novu-dispatch'
    | '/api/notification/resend-dispatch'
    | '/api/notification/resend-webhook'
    | '/api/observability/funnel'
    | '/api/storefront/import-draft'
    | '/_operator/admin/business-actions/$requestId'
    | '/_operator/admin/monetization/$operationId'
    | '/_operator/admin/protected-actions/$proposalId'
    | '/_operator/admin/runs/$turnId'
    | '/_operator/owner/actions/$proposalId'
    | '/_operator/owner/billing/activate'
    | '/_operator/owner/billing/redirecting'
    | '/_operator/owner/business-actions/$requestId'
    | '/_operator/owner/inquiries/$threadId'
    | '/api/answer/threads/$threadId'
    | '/_operator/owner/actions/$proposalId/receipt'
    | '/_operator/owner/billing/cancel/$operationId'
    | '/_operator/owner/billing/receipts/$receiptId'
    | '/_operator/owner/billing/return/$operationId'
    | '/_operator/owner/business-actions/$requestId/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  SKILLDotmdRoute: typeof SKILLDotmdRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  AboutRoute: typeof AboutRoute
  ClaimRoute: typeof ClaimRouteWithChildren
  HelpRoute: typeof HelpRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRouteWithChildren
  RRoute: typeof RRouteWithChildren
  RegistryRoute: typeof RegistryRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownHttpMessageSignaturesDirectoryRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  ApiAnswerRoute: typeof ApiAnswerRouteWithChildren
  ApiBusinessesRoute: typeof ApiBusinessesRouteWithChildren
  ApiChatRoute: typeof ApiChatRouteWithChildren
  IThreadIdRoute: typeof IThreadIdRoute
  QAnswerIdRoute: typeof QAnswerIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TThreadIdRoute: typeof TThreadIdRoute
  ApiAgentToolsRoute: typeof ApiAgentToolsRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiBusinessActionsStripeWebhookRoute: typeof ApiBusinessActionsStripeWebhookRoute
  ApiDiscoveryExamplesRoute: typeof ApiDiscoveryExamplesRoute
  ApiDiscoveryFixturesRoute: typeof ApiDiscoveryFixturesRoute
  ApiDiscoverySchemaRoute: typeof ApiDiscoverySchemaRoute
  ApiNotificationNovuDispatchRoute: typeof ApiNotificationNovuDispatchRoute
  ApiNotificationResendDispatchRoute: typeof ApiNotificationResendDispatchRoute
  ApiNotificationResendWebhookRoute: typeof ApiNotificationResendWebhookRoute
  ApiObservabilityFunnelRoute: typeof ApiObservabilityFunnelRoute
  ApiStorefrontImportDraftRoute: typeof ApiStorefrontImportDraftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator': {
      id: '/_operator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SKILL.md': {
      id: '/SKILL.md'
      path: '/SKILL.md'
      fullPath: '/SKILL.md'
      preLoaderRoute: typeof SKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$threadId': {
      id: '/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/t/$threadId'
      preLoaderRoute: typeof TThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$requestId': {
      id: '/r/$requestId'
      path: '/$requestId'
      fullPath: '/r/$requestId'
      preLoaderRoute: typeof RRequestIdRouteImport
      parentRoute: typeof RRoute
    }
    '/q/$answerId': {
      id: '/q/$answerId'
      path: '/q/$answerId'
      fullPath: '/q/$answerId'
      preLoaderRoute: typeof QAnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/remove-business': {
      id: '/privacy/remove-business'
      path: '/remove-business'
      fullPath: '/privacy/remove-business'
      preLoaderRoute: typeof PrivacyRemoveBusinessRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/i/$threadId': {
      id: '/i/$threadId'
      path: '/i/$threadId'
      fullPath: '/i/$threadId'
      preLoaderRoute: typeof IThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/success': {
      id: '/claim/success'
      path: '/success'
      fullPath: '/claim/success'
      preLoaderRoute: typeof ClaimSuccessRouteImport
      parentRoute: typeof ClaimRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses': {
      id: '/api/businesses'
      path: '/api/businesses'
      fullPath: '/api/businesses'
      preLoaderRoute: typeof ApiBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answer': {
      id: '/api/answer'
      path: '/api/answer'
      fullPath: '/api/answer'
      preLoaderRoute: typeof ApiAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/http-message-signatures-directory': {
      id: '/.well-known/http-message-signatures-directory'
      path: '/.well-known/http-message-signatures-directory'
      fullPath: '/.well-known/http-message-signatures-directory'
      preLoaderRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/ucp': {
      id: '/$slug/ucp'
      path: '/ucp'
      fullPath: '/$slug/ucp'
      preLoaderRoute: typeof SlugUcpRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/inquiry': {
      id: '/$slug/inquiry'
      path: '/inquiry'
      fullPath: '/$slug/inquiry'
      preLoaderRoute: typeof SlugInquiryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/api/storefront/import-draft': {
      id: '/api/storefront/import-draft'
      path: '/api/storefront/import-draft'
      fullPath: '/api/storefront/import-draft'
      preLoaderRoute: typeof ApiStorefrontImportDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/funnel': {
      id: '/api/observability/funnel'
      path: '/api/observability/funnel'
      fullPath: '/api/observability/funnel'
      preLoaderRoute: typeof ApiObservabilityFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification/resend-webhook': {
      id: '/api/notification/resend-webhook'
      path: '/api/notification/resend-webhook'
      fullPath: '/api/notification/resend-webhook'
      preLoaderRoute: typeof ApiNotificationResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification/resend-dispatch': {
      id: '/api/notification/resend-dispatch'
      path: '/api/notification/resend-dispatch'
      fullPath: '/api/notification/resend-dispatch'
      preLoaderRoute: typeof ApiNotificationResendDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification/novu-dispatch': {
      id: '/api/notification/novu-dispatch'
      path: '/api/notification/novu-dispatch'
      fullPath: '/api/notification/novu-dispatch'
      preLoaderRoute: typeof ApiNotificationNovuDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/schema': {
      id: '/api/discovery/schema'
      path: '/api/discovery/schema'
      fullPath: '/api/discovery/schema'
      preLoaderRoute: typeof ApiDiscoverySchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/fixtures': {
      id: '/api/discovery/fixtures'
      path: '/api/discovery/fixtures'
      fullPath: '/api/discovery/fixtures'
      preLoaderRoute: typeof ApiDiscoveryFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/examples': {
      id: '/api/discovery/examples'
      path: '/api/discovery/examples'
      fullPath: '/api/discovery/examples'
      preLoaderRoute: typeof ApiDiscoveryExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/models': {
      id: '/api/chat/models'
      path: '/models'
      fullPath: '/api/chat/models'
      preLoaderRoute: typeof ApiChatModelsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/businesses/search': {
      id: '/api/businesses/search'
      path: '/search'
      fullPath: '/api/businesses/search'
      preLoaderRoute: typeof ApiBusinessesSearchRouteImport
      parentRoute: typeof ApiBusinessesRoute
    }
    '/api/businesses/$slug': {
      id: '/api/businesses/$slug'
      path: '/$slug'
      fullPath: '/api/businesses/$slug'
      preLoaderRoute: typeof ApiBusinessesSlugRouteImport
      parentRoute: typeof ApiBusinessesRoute
    }
    '/api/business-actions/stripe-webhook': {
      id: '/api/business-actions/stripe-webhook'
      path: '/api/business-actions/stripe-webhook'
      fullPath: '/api/business-actions/stripe-webhook'
      preLoaderRoute: typeof ApiBusinessActionsStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answer/turn': {
      id: '/api/answer/turn'
      path: '/turn'
      fullPath: '/api/answer/turn'
      preLoaderRoute: typeof ApiAnswerTurnRouteImport
      parentRoute: typeof ApiAnswerRoute
    }
    '/api/answer/threads': {
      id: '/api/answer/threads'
      path: '/threads'
      fullPath: '/api/answer/threads'
      preLoaderRoute: typeof ApiAnswerThreadsRouteImport
      parentRoute: typeof ApiAnswerRoute
    }
    '/api/answer/follow-up-chips': {
      id: '/api/answer/follow-up-chips'
      path: '/follow-up-chips'
      fullPath: '/api/answer/follow-up-chips'
      preLoaderRoute: typeof ApiAnswerFollowUpChipsRouteImport
      parentRoute: typeof ApiAnswerRoute
    }
    '/api/answer/eval-status': {
      id: '/api/answer/eval-status'
      path: '/eval-status'
      fullPath: '/api/answer/eval-status'
      preLoaderRoute: typeof ApiAnswerEvalStatusRouteImport
      parentRoute: typeof ApiAnswerRoute
    }
    '/api/agent/tools': {
      id: '/api/agent/tools'
      path: '/api/agent/tools'
      fullPath: '/api/agent/tools'
      preLoaderRoute: typeof ApiAgentToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/owner/status': {
      id: '/_operator/owner/status'
      path: '/owner/status'
      fullPath: '/owner/status'
      preLoaderRoute: typeof OperatorOwnerStatusRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/settings': {
      id: '/_operator/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OperatorOwnerSettingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/inquiries': {
      id: '/_operator/owner/inquiries'
      path: '/owner/inquiries'
      fullPath: '/owner/inquiries'
      preLoaderRoute: typeof OperatorOwnerInquiriesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/business-actions': {
      id: '/_operator/owner/business-actions'
      path: '/owner/business-actions'
      fullPath: '/owner/business-actions'
      preLoaderRoute: typeof OperatorOwnerBusinessActionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/billing': {
      id: '/_operator/owner/billing'
      path: '/owner/billing'
      fullPath: '/owner/billing'
      preLoaderRoute: typeof OperatorOwnerBillingRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/actions': {
      id: '/_operator/owner/actions'
      path: '/owner/actions'
      fullPath: '/owner/actions'
      preLoaderRoute: typeof OperatorOwnerActionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/developers/discovery': {
      id: '/_operator/developers/discovery'
      path: '/developers/discovery'
      fullPath: '/developers/discovery'
      preLoaderRoute: typeof OperatorDevelopersDiscoveryRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/runs': {
      id: '/_operator/admin/runs'
      path: '/admin/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof OperatorAdminRunsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/protected-actions': {
      id: '/_operator/admin/protected-actions'
      path: '/admin/protected-actions'
      fullPath: '/admin/protected-actions'
      preLoaderRoute: typeof OperatorAdminProtectedActionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/monetization': {
      id: '/_operator/admin/monetization'
      path: '/admin/monetization'
      fullPath: '/admin/monetization'
      preLoaderRoute: typeof OperatorAdminMonetizationRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/inquiries': {
      id: '/_operator/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof OperatorAdminInquiriesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/index-health': {
      id: '/_operator/admin/index-health'
      path: '/admin/index-health'
      fullPath: '/admin/index-health'
      preLoaderRoute: typeof OperatorAdminIndexHealthRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/claims': {
      id: '/_operator/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof OperatorAdminClaimsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/business-actions': {
      id: '/_operator/admin/business-actions'
      path: '/admin/business-actions'
      fullPath: '/admin/business-actions'
      preLoaderRoute: typeof OperatorAdminBusinessActionsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/audit-events': {
      id: '/_operator/admin/audit-events'
      path: '/admin/audit-events'
      fullPath: '/admin/audit-events'
      preLoaderRoute: typeof OperatorAdminAuditEventsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/api/answer/threads/$threadId': {
      id: '/api/answer/threads/$threadId'
      path: '/$threadId'
      fullPath: '/api/answer/threads/$threadId'
      preLoaderRoute: typeof ApiAnswerThreadsThreadIdRouteImport
      parentRoute: typeof ApiAnswerThreadsRoute
    }
    '/_operator/owner/inquiries/$threadId': {
      id: '/_operator/owner/inquiries/$threadId'
      path: '/$threadId'
      fullPath: '/owner/inquiries/$threadId'
      preLoaderRoute: typeof OperatorOwnerInquiriesThreadIdRouteImport
      parentRoute: typeof OperatorOwnerInquiriesRoute
    }
    '/_operator/owner/business-actions/$requestId': {
      id: '/_operator/owner/business-actions/$requestId'
      path: '/$requestId'
      fullPath: '/owner/business-actions/$requestId'
      preLoaderRoute: typeof OperatorOwnerBusinessActionsRequestIdRouteImport
      parentRoute: typeof OperatorOwnerBusinessActionsRoute
    }
    '/_operator/owner/billing/redirecting': {
      id: '/_operator/owner/billing/redirecting'
      path: '/redirecting'
      fullPath: '/owner/billing/redirecting'
      preLoaderRoute: typeof OperatorOwnerBillingRedirectingRouteImport
      parentRoute: typeof OperatorOwnerBillingRoute
    }
    '/_operator/owner/billing/activate': {
      id: '/_operator/owner/billing/activate'
      path: '/activate'
      fullPath: '/owner/billing/activate'
      preLoaderRoute: typeof OperatorOwnerBillingActivateRouteImport
      parentRoute: typeof OperatorOwnerBillingRoute
    }
    '/_operator/owner/actions/$proposalId': {
      id: '/_operator/owner/actions/$proposalId'
      path: '/$proposalId'
      fullPath: '/owner/actions/$proposalId'
      preLoaderRoute: typeof OperatorOwnerActionsProposalIdRouteImport
      parentRoute: typeof OperatorOwnerActionsRoute
    }
    '/_operator/admin/runs/$turnId': {
      id: '/_operator/admin/runs/$turnId'
      path: '/$turnId'
      fullPath: '/admin/runs/$turnId'
      preLoaderRoute: typeof OperatorAdminRunsTurnIdRouteImport
      parentRoute: typeof OperatorAdminRunsRoute
    }
    '/_operator/admin/protected-actions/$proposalId': {
      id: '/_operator/admin/protected-actions/$proposalId'
      path: '/$proposalId'
      fullPath: '/admin/protected-actions/$proposalId'
      preLoaderRoute: typeof OperatorAdminProtectedActionsProposalIdRouteImport
      parentRoute: typeof OperatorAdminProtectedActionsRoute
    }
    '/_operator/admin/monetization/$operationId': {
      id: '/_operator/admin/monetization/$operationId'
      path: '/$operationId'
      fullPath: '/admin/monetization/$operationId'
      preLoaderRoute: typeof OperatorAdminMonetizationOperationIdRouteImport
      parentRoute: typeof OperatorAdminMonetizationRoute
    }
    '/_operator/admin/business-actions/$requestId': {
      id: '/_operator/admin/business-actions/$requestId'
      path: '/$requestId'
      fullPath: '/admin/business-actions/$requestId'
      preLoaderRoute: typeof OperatorAdminBusinessActionsRequestIdRouteImport
      parentRoute: typeof OperatorAdminBusinessActionsRoute
    }
    '/_operator/owner/business-actions/$requestId/receipt': {
      id: '/_operator/owner/business-actions/$requestId/receipt'
      path: '/receipt'
      fullPath: '/owner/business-actions/$requestId/receipt'
      preLoaderRoute: typeof OperatorOwnerBusinessActionsRequestIdReceiptRouteImport
      parentRoute: typeof OperatorOwnerBusinessActionsRequestIdRoute
    }
    '/_operator/owner/billing/return/$operationId': {
      id: '/_operator/owner/billing/return/$operationId'
      path: '/return/$operationId'
      fullPath: '/owner/billing/return/$operationId'
      preLoaderRoute: typeof OperatorOwnerBillingReturnOperationIdRouteImport
      parentRoute: typeof OperatorOwnerBillingRoute
    }
    '/_operator/owner/billing/receipts/$receiptId': {
      id: '/_operator/owner/billing/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/owner/billing/receipts/$receiptId'
      preLoaderRoute: typeof OperatorOwnerBillingReceiptsReceiptIdRouteImport
      parentRoute: typeof OperatorOwnerBillingRoute
    }
    '/_operator/owner/billing/cancel/$operationId': {
      id: '/_operator/owner/billing/cancel/$operationId'
      path: '/cancel/$operationId'
      fullPath: '/owner/billing/cancel/$operationId'
      preLoaderRoute: typeof OperatorOwnerBillingCancelOperationIdRouteImport
      parentRoute: typeof OperatorOwnerBillingRoute
    }
    '/_operator/owner/actions/$proposalId/receipt': {
      id: '/_operator/owner/actions/$proposalId/receipt'
      path: '/receipt'
      fullPath: '/owner/actions/$proposalId/receipt'
      preLoaderRoute: typeof OperatorOwnerActionsProposalIdReceiptRouteImport
      parentRoute: typeof OperatorOwnerActionsProposalIdRoute
    }
  }
}

interface SlugRouteChildren {
  SlugInquiryRoute: typeof SlugInquiryRoute
  SlugUcpRoute: typeof SlugUcpRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugInquiryRoute: SlugInquiryRoute,
  SlugUcpRoute: SlugUcpRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface OperatorAdminBusinessActionsRouteChildren {
  OperatorAdminBusinessActionsRequestIdRoute: typeof OperatorAdminBusinessActionsRequestIdRoute
}

const OperatorAdminBusinessActionsRouteChildren: OperatorAdminBusinessActionsRouteChildren =
  {
    OperatorAdminBusinessActionsRequestIdRoute:
      OperatorAdminBusinessActionsRequestIdRoute,
  }

const OperatorAdminBusinessActionsRouteWithChildren =
  OperatorAdminBusinessActionsRoute._addFileChildren(
    OperatorAdminBusinessActionsRouteChildren,
  )

interface OperatorAdminMonetizationRouteChildren {
  OperatorAdminMonetizationOperationIdRoute: typeof OperatorAdminMonetizationOperationIdRoute
}

const OperatorAdminMonetizationRouteChildren: OperatorAdminMonetizationRouteChildren =
  {
    OperatorAdminMonetizationOperationIdRoute:
      OperatorAdminMonetizationOperationIdRoute,
  }

const OperatorAdminMonetizationRouteWithChildren =
  OperatorAdminMonetizationRoute._addFileChildren(
    OperatorAdminMonetizationRouteChildren,
  )

interface OperatorAdminProtectedActionsRouteChildren {
  OperatorAdminProtectedActionsProposalIdRoute: typeof OperatorAdminProtectedActionsProposalIdRoute
}

const OperatorAdminProtectedActionsRouteChildren: OperatorAdminProtectedActionsRouteChildren =
  {
    OperatorAdminProtectedActionsProposalIdRoute:
      OperatorAdminProtectedActionsProposalIdRoute,
  }

const OperatorAdminProtectedActionsRouteWithChildren =
  OperatorAdminProtectedActionsRoute._addFileChildren(
    OperatorAdminProtectedActionsRouteChildren,
  )

interface OperatorAdminRunsRouteChildren {
  OperatorAdminRunsTurnIdRoute: typeof OperatorAdminRunsTurnIdRoute
}

const OperatorAdminRunsRouteChildren: OperatorAdminRunsRouteChildren = {
  OperatorAdminRunsTurnIdRoute: OperatorAdminRunsTurnIdRoute,
}

const OperatorAdminRunsRouteWithChildren =
  OperatorAdminRunsRoute._addFileChildren(OperatorAdminRunsRouteChildren)

interface OperatorOwnerActionsProposalIdRouteChildren {
  OperatorOwnerActionsProposalIdReceiptRoute: typeof OperatorOwnerActionsProposalIdReceiptRoute
}

const OperatorOwnerActionsProposalIdRouteChildren: OperatorOwnerActionsProposalIdRouteChildren =
  {
    OperatorOwnerActionsProposalIdReceiptRoute:
      OperatorOwnerActionsProposalIdReceiptRoute,
  }

const OperatorOwnerActionsProposalIdRouteWithChildren =
  OperatorOwnerActionsProposalIdRoute._addFileChildren(
    OperatorOwnerActionsProposalIdRouteChildren,
  )

interface OperatorOwnerActionsRouteChildren {
  OperatorOwnerActionsProposalIdRoute: typeof OperatorOwnerActionsProposalIdRouteWithChildren
}

const OperatorOwnerActionsRouteChildren: OperatorOwnerActionsRouteChildren = {
  OperatorOwnerActionsProposalIdRoute:
    OperatorOwnerActionsProposalIdRouteWithChildren,
}

const OperatorOwnerActionsRouteWithChildren =
  OperatorOwnerActionsRoute._addFileChildren(OperatorOwnerActionsRouteChildren)

interface OperatorOwnerBillingRouteChildren {
  OperatorOwnerBillingActivateRoute: typeof OperatorOwnerBillingActivateRoute
  OperatorOwnerBillingRedirectingRoute: typeof OperatorOwnerBillingRedirectingRoute
  OperatorOwnerBillingCancelOperationIdRoute: typeof OperatorOwnerBillingCancelOperationIdRoute
  OperatorOwnerBillingReceiptsReceiptIdRoute: typeof OperatorOwnerBillingReceiptsReceiptIdRoute
  OperatorOwnerBillingReturnOperationIdRoute: typeof OperatorOwnerBillingReturnOperationIdRoute
}

const OperatorOwnerBillingRouteChildren: OperatorOwnerBillingRouteChildren = {
  OperatorOwnerBillingActivateRoute: OperatorOwnerBillingActivateRoute,
  OperatorOwnerBillingRedirectingRoute: OperatorOwnerBillingRedirectingRoute,
  OperatorOwnerBillingCancelOperationIdRoute:
    OperatorOwnerBillingCancelOperationIdRoute,
  OperatorOwnerBillingReceiptsReceiptIdRoute:
    OperatorOwnerBillingReceiptsReceiptIdRoute,
  OperatorOwnerBillingReturnOperationIdRoute:
    OperatorOwnerBillingReturnOperationIdRoute,
}

const OperatorOwnerBillingRouteWithChildren =
  OperatorOwnerBillingRoute._addFileChildren(OperatorOwnerBillingRouteChildren)

interface OperatorOwnerBusinessActionsRequestIdRouteChildren {
  OperatorOwnerBusinessActionsRequestIdReceiptRoute: typeof OperatorOwnerBusinessActionsRequestIdReceiptRoute
}

const OperatorOwnerBusinessActionsRequestIdRouteChildren: OperatorOwnerBusinessActionsRequestIdRouteChildren =
  {
    OperatorOwnerBusinessActionsRequestIdReceiptRoute:
      OperatorOwnerBusinessActionsRequestIdReceiptRoute,
  }

const OperatorOwnerBusinessActionsRequestIdRouteWithChildren =
  OperatorOwnerBusinessActionsRequestIdRoute._addFileChildren(
    OperatorOwnerBusinessActionsRequestIdRouteChildren,
  )

interface OperatorOwnerBusinessActionsRouteChildren {
  OperatorOwnerBusinessActionsRequestIdRoute: typeof OperatorOwnerBusinessActionsRequestIdRouteWithChildren
}

const OperatorOwnerBusinessActionsRouteChildren: OperatorOwnerBusinessActionsRouteChildren =
  {
    OperatorOwnerBusinessActionsRequestIdRoute:
      OperatorOwnerBusinessActionsRequestIdRouteWithChildren,
  }

const OperatorOwnerBusinessActionsRouteWithChildren =
  OperatorOwnerBusinessActionsRoute._addFileChildren(
    OperatorOwnerBusinessActionsRouteChildren,
  )

interface OperatorOwnerInquiriesRouteChildren {
  OperatorOwnerInquiriesThreadIdRoute: typeof OperatorOwnerInquiriesThreadIdRoute
}

const OperatorOwnerInquiriesRouteChildren: OperatorOwnerInquiriesRouteChildren =
  {
    OperatorOwnerInquiriesThreadIdRoute: OperatorOwnerInquiriesThreadIdRoute,
  }

const OperatorOwnerInquiriesRouteWithChildren =
  OperatorOwnerInquiriesRoute._addFileChildren(
    OperatorOwnerInquiriesRouteChildren,
  )

interface OperatorRouteChildren {
  OperatorAdminAuditEventsRoute: typeof OperatorAdminAuditEventsRoute
  OperatorAdminBusinessActionsRoute: typeof OperatorAdminBusinessActionsRouteWithChildren
  OperatorAdminClaimsRoute: typeof OperatorAdminClaimsRoute
  OperatorAdminIndexHealthRoute: typeof OperatorAdminIndexHealthRoute
  OperatorAdminInquiriesRoute: typeof OperatorAdminInquiriesRoute
  OperatorAdminMonetizationRoute: typeof OperatorAdminMonetizationRouteWithChildren
  OperatorAdminProtectedActionsRoute: typeof OperatorAdminProtectedActionsRouteWithChildren
  OperatorAdminRunsRoute: typeof OperatorAdminRunsRouteWithChildren
  OperatorDevelopersDiscoveryRoute: typeof OperatorDevelopersDiscoveryRoute
  OperatorOwnerActionsRoute: typeof OperatorOwnerActionsRouteWithChildren
  OperatorOwnerBillingRoute: typeof OperatorOwnerBillingRouteWithChildren
  OperatorOwnerBusinessActionsRoute: typeof OperatorOwnerBusinessActionsRouteWithChildren
  OperatorOwnerInquiriesRoute: typeof OperatorOwnerInquiriesRouteWithChildren
  OperatorOwnerSettingsRoute: typeof OperatorOwnerSettingsRoute
  OperatorOwnerStatusRoute: typeof OperatorOwnerStatusRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAdminAuditEventsRoute: OperatorAdminAuditEventsRoute,
  OperatorAdminBusinessActionsRoute:
    OperatorAdminBusinessActionsRouteWithChildren,
  OperatorAdminClaimsRoute: OperatorAdminClaimsRoute,
  OperatorAdminIndexHealthRoute: OperatorAdminIndexHealthRoute,
  OperatorAdminInquiriesRoute: OperatorAdminInquiriesRoute,
  OperatorAdminMonetizationRoute: OperatorAdminMonetizationRouteWithChildren,
  OperatorAdminProtectedActionsRoute:
    OperatorAdminProtectedActionsRouteWithChildren,
  OperatorAdminRunsRoute: OperatorAdminRunsRouteWithChildren,
  OperatorDevelopersDiscoveryRoute: OperatorDevelopersDiscoveryRoute,
  OperatorOwnerActionsRoute: OperatorOwnerActionsRouteWithChildren,
  OperatorOwnerBillingRoute: OperatorOwnerBillingRouteWithChildren,
  OperatorOwnerBusinessActionsRoute:
    OperatorOwnerBusinessActionsRouteWithChildren,
  OperatorOwnerInquiriesRoute: OperatorOwnerInquiriesRouteWithChildren,
  OperatorOwnerSettingsRoute: OperatorOwnerSettingsRoute,
  OperatorOwnerStatusRoute: OperatorOwnerStatusRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface ClaimRouteChildren {
  ClaimSuccessRoute: typeof ClaimSuccessRoute
}

const ClaimRouteChildren: ClaimRouteChildren = {
  ClaimSuccessRoute: ClaimSuccessRoute,
}

const ClaimRouteWithChildren = ClaimRoute._addFileChildren(ClaimRouteChildren)

interface PrivacyRouteChildren {
  PrivacyRemoveBusinessRoute: typeof PrivacyRemoveBusinessRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacyRemoveBusinessRoute: PrivacyRemoveBusinessRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface RRouteChildren {
  RRequestIdRoute: typeof RRequestIdRoute
}

const RRouteChildren: RRouteChildren = {
  RRequestIdRoute: RRequestIdRoute,
}

const RRouteWithChildren = RRoute._addFileChildren(RRouteChildren)

interface ApiAnswerThreadsRouteChildren {
  ApiAnswerThreadsThreadIdRoute: typeof ApiAnswerThreadsThreadIdRoute
}

const ApiAnswerThreadsRouteChildren: ApiAnswerThreadsRouteChildren = {
  ApiAnswerThreadsThreadIdRoute: ApiAnswerThreadsThreadIdRoute,
}

const ApiAnswerThreadsRouteWithChildren =
  ApiAnswerThreadsRoute._addFileChildren(ApiAnswerThreadsRouteChildren)

interface ApiAnswerRouteChildren {
  ApiAnswerEvalStatusRoute: typeof ApiAnswerEvalStatusRoute
  ApiAnswerFollowUpChipsRoute: typeof ApiAnswerFollowUpChipsRoute
  ApiAnswerThreadsRoute: typeof ApiAnswerThreadsRouteWithChildren
  ApiAnswerTurnRoute: typeof ApiAnswerTurnRoute
}

const ApiAnswerRouteChildren: ApiAnswerRouteChildren = {
  ApiAnswerEvalStatusRoute: ApiAnswerEvalStatusRoute,
  ApiAnswerFollowUpChipsRoute: ApiAnswerFollowUpChipsRoute,
  ApiAnswerThreadsRoute: ApiAnswerThreadsRouteWithChildren,
  ApiAnswerTurnRoute: ApiAnswerTurnRoute,
}

const ApiAnswerRouteWithChildren = ApiAnswerRoute._addFileChildren(
  ApiAnswerRouteChildren,
)

interface ApiBusinessesRouteChildren {
  ApiBusinessesSlugRoute: typeof ApiBusinessesSlugRoute
  ApiBusinessesSearchRoute: typeof ApiBusinessesSearchRoute
}

const ApiBusinessesRouteChildren: ApiBusinessesRouteChildren = {
  ApiBusinessesSlugRoute: ApiBusinessesSlugRoute,
  ApiBusinessesSearchRoute: ApiBusinessesSearchRoute,
}

const ApiBusinessesRouteWithChildren = ApiBusinessesRoute._addFileChildren(
  ApiBusinessesRouteChildren,
)

interface ApiChatRouteChildren {
  ApiChatModelsRoute: typeof ApiChatModelsRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatModelsRoute: ApiChatModelsRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  SKILLDotmdRoute: SKILLDotmdRoute,
  OperatorRoute: OperatorRouteWithChildren,
  AboutRoute: AboutRoute,
  ClaimRoute: ClaimRouteWithChildren,
  HelpRoute: HelpRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRouteWithChildren,
  RRoute: RRouteWithChildren,
  RegistryRoute: RegistryRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DotwellKnownHttpMessageSignaturesDirectoryRoute:
    DotwellKnownHttpMessageSignaturesDirectoryRoute,
  ApiAnswerRoute: ApiAnswerRouteWithChildren,
  ApiBusinessesRoute: ApiBusinessesRouteWithChildren,
  ApiChatRoute: ApiChatRouteWithChildren,
  IThreadIdRoute: IThreadIdRoute,
  QAnswerIdRoute: QAnswerIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TThreadIdRoute: TThreadIdRoute,
  ApiAgentToolsRoute: ApiAgentToolsRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiBusinessActionsStripeWebhookRoute: ApiBusinessActionsStripeWebhookRoute,
  ApiDiscoveryExamplesRoute: ApiDiscoveryExamplesRoute,
  ApiDiscoveryFixturesRoute: ApiDiscoveryFixturesRoute,
  ApiDiscoverySchemaRoute: ApiDiscoverySchemaRoute,
  ApiNotificationNovuDispatchRoute: ApiNotificationNovuDispatchRoute,
  ApiNotificationResendDispatchRoute: ApiNotificationResendDispatchRoute,
  ApiNotificationResendWebhookRoute: ApiNotificationResendWebhookRoute,
  ApiObservabilityFunnelRoute: ApiObservabilityFunnelRoute,
  ApiStorefrontImportDraftRoute: ApiStorefrontImportDraftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
