/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as OperatorRouteImport } from './routes/_operator'
import { Route as SKILLDotmdRouteImport } from './routes/SKILL[.]md'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TNewRouteImport } from './routes/t.new'
import { Route as TThreadIdRouteImport } from './routes/t.$threadId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SShareTokenRouteImport } from './routes/s.$shareToken'
import { Route as PrivacyRemoveBusinessRouteImport } from './routes/privacy.remove-business'
import { Route as OperationsOperationRefRouteImport } from './routes/operations.$operationRef'
import { Route as OauthTokenRouteImport } from './routes/oauth.token'
import { Route as OauthRegisterRouteImport } from './routes/oauth.register'
import { Route as OauthDevice_authorizationRouteImport } from './routes/oauth.device_authorization'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiBusinessesRouteImport } from './routes/api.businesses'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as OperatorAgentAccessRouteImport } from './routes/_operator/agent-access'
import { Route as OperatorActivityRouteImport } from './routes/_operator/activity'
import { Route as DotwellKnownUcpRouteImport } from './routes/[.]well-known/ucp'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownHttpMessageSignaturesDirectoryRouteImport } from './routes/[.]well-known/http-message-signatures-directory'
import { Route as SlugUcpRouteImport } from './routes/$slug.ucp'
import { Route as OperationsInvocationsInvocationRefRouteImport } from './routes/operations.invocations.$invocationRef'
import { Route as ApiV1ServicesRouteImport } from './routes/api.v1.services'
import { Route as ApiV1ReleaseRouteImport } from './routes/api.v1.release'
import { Route as ApiV1RegistryRouteImport } from './routes/api.v1.registry'
import { Route as ApiV1MarketMetricsRouteImport } from './routes/api.v1.market-metrics'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiObservabilityClientErrorRouteImport } from './routes/api.observability.client-error'
import { Route as ApiDiscoverySchemaRouteImport } from './routes/api.discovery.schema'
import { Route as ApiDiscoveryExamplesRouteImport } from './routes/api.discovery.examples'
import { Route as ApiChatAnonymousRouteImport } from './routes/api.chat.anonymous'
import { Route as ApiBusinessesSearchRouteImport } from './routes/api.businesses.search'
import { Route as ApiBusinessesSlugRouteImport } from './routes/api.businesses.$slug'
import { Route as OperatorOwnerSupplyRouteImport } from './routes/_operator/owner.supply'
import { Route as OperatorOwnerStatusRouteImport } from './routes/_operator/owner.status'
import { Route as OperatorOwnerSettingsRouteImport } from './routes/_operator/owner.settings'
import { Route as OperatorOwnerOfferingsRouteImport } from './routes/_operator/owner.offerings'
import { Route as OperatorOwnerCreditRouteImport } from './routes/_operator/owner.credit'
import { Route as OperatorDevelopersDiscoveryRouteImport } from './routes/_operator/developers.discovery'
import { Route as OperatorAgentAccessAuthorizeRouteImport } from './routes/_operator/agent-access.authorize'
import { Route as OperatorAdminIndexHealthRouteImport } from './routes/_operator/admin.index-health'
import { Route as OperatorAdminAuditEventsRouteImport } from './routes/_operator/admin.audit-events'
import { Route as ApiV1ServicesSearchRouteImport } from './routes/api.v1.services.search'
import { Route as ApiV1ServicesServiceIdRouteImport } from './routes/api.v1.services.$serviceId'
import { Route as ApiV1OperationsCallRouteImport } from './routes/api.v1.operations.call'
import { Route as ApiV1OperationsInvocationRefRouteImport } from './routes/api.v1.operations.$invocationRef'
import { Route as ApiV1MarketOperationsSearchRouteImport } from './routes/api.v1.market-operations.search'
import { Route as ApiV1MarketOperationsInspectPlanRouteImport } from './routes/api.v1.market-operations.inspect-plan'
import { Route as ApiV1MarketOperationsDetailRouteImport } from './routes/api.v1.market-operations.detail'
import { Route as ApiV1MarketOperationsCompareRouteImport } from './routes/api.v1.market-operations.compare'
import { Route as OperatorOwnerSupplyOfferingRefRouteImport } from './routes/_operator/owner.supply.$offeringRef'
import { Route as OperatorOwnerOfferingsNewRouteImport } from './routes/_operator/owner.offerings.new'
import { Route as OperatorOwnerOfferingsOfferingRefRouteImport } from './routes/_operator/owner.offerings.$offeringRef'
import { Route as ApiV1OperationsInvocationRefReconcileRouteImport } from './routes/api.v1.operations.$invocationRef.reconcile'
import { Route as ApiV1OperationsInvocationRefCancelRouteImport } from './routes/api.v1.operations.$invocationRef.cancel'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => rootRouteImport,
} as any)
const SKILLDotmdRoute = SKILLDotmdRouteImport.update({
  id: '/SKILL.md',
  path: '/SKILL.md',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TNewRoute = TNewRouteImport.update({
  id: '/t/new',
  path: '/t/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TThreadIdRoute = TThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareTokenRoute = SShareTokenRouteImport.update({
  id: '/s/$shareToken',
  path: '/s/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRemoveBusinessRoute = PrivacyRemoveBusinessRouteImport.update({
  id: '/remove-business',
  path: '/remove-business',
  getParentRoute: () => PrivacyRoute,
} as any)
const OperationsOperationRefRoute = OperationsOperationRefRouteImport.update({
  id: '/$operationRef',
  path: '/$operationRef',
  getParentRoute: () => OperationsRoute,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthDevice_authorizationRoute =
  OauthDevice_authorizationRouteImport.update({
    id: '/oauth/device_authorization',
    path: '/oauth/device_authorization',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesRoute = ApiBusinessesRouteImport.update({
  id: '/api/businesses',
  path: '/api/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorAgentAccessRoute = OperatorAgentAccessRouteImport.update({
  id: '/agent-access',
  path: '/agent-access',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorActivityRoute = OperatorActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OperatorRoute,
} as any)
const DotwellKnownUcpRoute = DotwellKnownUcpRouteImport.update({
  id: '/.well-known/ucp',
  path: '/.well-known/ucp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownHttpMessageSignaturesDirectoryRoute =
  DotwellKnownHttpMessageSignaturesDirectoryRouteImport.update({
    id: '/.well-known/http-message-signatures-directory',
    path: '/.well-known/http-message-signatures-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugUcpRoute = SlugUcpRouteImport.update({
  id: '/ucp',
  path: '/ucp',
  getParentRoute: () => SlugRoute,
} as any)
const OperationsInvocationsInvocationRefRoute =
  OperationsInvocationsInvocationRefRouteImport.update({
    id: '/invocations/$invocationRef',
    path: '/invocations/$invocationRef',
    getParentRoute: () => OperationsRoute,
  } as any)
const ApiV1ServicesRoute = ApiV1ServicesRouteImport.update({
  id: '/api/v1/services',
  path: '/api/v1/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReleaseRoute = ApiV1ReleaseRouteImport.update({
  id: '/api/v1/release',
  path: '/api/v1/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RegistryRoute = ApiV1RegistryRouteImport.update({
  id: '/api/v1/registry',
  path: '/api/v1/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MarketMetricsRoute = ApiV1MarketMetricsRouteImport.update({
  id: '/api/v1/market-metrics',
  path: '/api/v1/market-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityClientErrorRoute =
  ApiObservabilityClientErrorRouteImport.update({
    id: '/api/observability/client-error',
    path: '/api/observability/client-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoverySchemaRoute = ApiDiscoverySchemaRouteImport.update({
  id: '/api/discovery/schema',
  path: '/api/discovery/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryExamplesRoute = ApiDiscoveryExamplesRouteImport.update({
  id: '/api/discovery/examples',
  path: '/api/discovery/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatAnonymousRoute = ApiChatAnonymousRouteImport.update({
  id: '/api/chat/anonymous',
  path: '/api/chat/anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessesSearchRoute = ApiBusinessesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiBusinessesRoute,
} as any)
const ApiBusinessesSlugRoute = ApiBusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBusinessesRoute,
} as any)
const OperatorOwnerSupplyRoute = OperatorOwnerSupplyRouteImport.update({
  id: '/owner/supply',
  path: '/owner/supply',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerStatusRoute = OperatorOwnerStatusRouteImport.update({
  id: '/owner/status',
  path: '/owner/status',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerSettingsRoute = OperatorOwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerOfferingsRoute = OperatorOwnerOfferingsRouteImport.update({
  id: '/owner/offerings',
  path: '/owner/offerings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOwnerCreditRoute = OperatorOwnerCreditRouteImport.update({
  id: '/owner/credit',
  path: '/owner/credit',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorDevelopersDiscoveryRoute =
  OperatorDevelopersDiscoveryRouteImport.update({
    id: '/developers/discovery',
    path: '/developers/discovery',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAgentAccessAuthorizeRoute =
  OperatorAgentAccessAuthorizeRouteImport.update({
    id: '/authorize',
    path: '/authorize',
    getParentRoute: () => OperatorAgentAccessRoute,
  } as any)
const OperatorAdminIndexHealthRoute =
  OperatorAdminIndexHealthRouteImport.update({
    id: '/admin/index-health',
    path: '/admin/index-health',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorAdminAuditEventsRoute =
  OperatorAdminAuditEventsRouteImport.update({
    id: '/admin/audit-events',
    path: '/admin/audit-events',
    getParentRoute: () => OperatorRoute,
  } as any)
const ApiV1ServicesSearchRoute = ApiV1ServicesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiV1ServicesRoute,
} as any)
const ApiV1ServicesServiceIdRoute = ApiV1ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ApiV1ServicesRoute,
} as any)
const ApiV1OperationsCallRoute = ApiV1OperationsCallRouteImport.update({
  id: '/api/v1/operations/call',
  path: '/api/v1/operations/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OperationsInvocationRefRoute =
  ApiV1OperationsInvocationRefRouteImport.update({
    id: '/api/v1/operations/$invocationRef',
    path: '/api/v1/operations/$invocationRef',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MarketOperationsSearchRoute =
  ApiV1MarketOperationsSearchRouteImport.update({
    id: '/api/v1/market-operations/search',
    path: '/api/v1/market-operations/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MarketOperationsInspectPlanRoute =
  ApiV1MarketOperationsInspectPlanRouteImport.update({
    id: '/api/v1/market-operations/inspect-plan',
    path: '/api/v1/market-operations/inspect-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MarketOperationsDetailRoute =
  ApiV1MarketOperationsDetailRouteImport.update({
    id: '/api/v1/market-operations/detail',
    path: '/api/v1/market-operations/detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MarketOperationsCompareRoute =
  ApiV1MarketOperationsCompareRouteImport.update({
    id: '/api/v1/market-operations/compare',
    path: '/api/v1/market-operations/compare',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperatorOwnerSupplyOfferingRefRoute =
  OperatorOwnerSupplyOfferingRefRouteImport.update({
    id: '/$offeringRef',
    path: '/$offeringRef',
    getParentRoute: () => OperatorOwnerSupplyRoute,
  } as any)
const OperatorOwnerOfferingsNewRoute =
  OperatorOwnerOfferingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => OperatorOwnerOfferingsRoute,
  } as any)
const OperatorOwnerOfferingsOfferingRefRoute =
  OperatorOwnerOfferingsOfferingRefRouteImport.update({
    id: '/$offeringRef',
    path: '/$offeringRef',
    getParentRoute: () => OperatorOwnerOfferingsRoute,
  } as any)
const ApiV1OperationsInvocationRefReconcileRoute =
  ApiV1OperationsInvocationRefReconcileRouteImport.update({
    id: '/reconcile',
    path: '/reconcile',
    getParentRoute: () => ApiV1OperationsInvocationRefRoute,
  } as any)
const ApiV1OperationsInvocationRefCancelRoute =
  ApiV1OperationsInvocationRefCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiV1OperationsInvocationRefRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/engine': typeof EngineRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-providers': typeof ForProvidersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/ucp': typeof DotwellKnownUcpRoute
  '/activity': typeof OperatorActivityRoute
  '/agent-access': typeof OperatorAgentAccessRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/device_authorization': typeof OauthDevice_authorizationRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/operations/$operationRef': typeof OperationsOperationRefRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/t/new': typeof TNewRoute
  '/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/agent-access/authorize': typeof OperatorAgentAccessAuthorizeRoute
  '/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/owner/credit': typeof OperatorOwnerCreditRoute
  '/owner/offerings': typeof OperatorOwnerOfferingsRouteWithChildren
  '/owner/settings': typeof OperatorOwnerSettingsRoute
  '/owner/status': typeof OperatorOwnerStatusRoute
  '/owner/supply': typeof OperatorOwnerSupplyRouteWithChildren
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/anonymous': typeof ApiChatAnonymousRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/observability/client-error': typeof ApiObservabilityClientErrorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/market-metrics': typeof ApiV1MarketMetricsRoute
  '/api/v1/registry': typeof ApiV1RegistryRoute
  '/api/v1/release': typeof ApiV1ReleaseRoute
  '/api/v1/services': typeof ApiV1ServicesRouteWithChildren
  '/operations/invocations/$invocationRef': typeof OperationsInvocationsInvocationRefRoute
  '/owner/offerings/$offeringRef': typeof OperatorOwnerOfferingsOfferingRefRoute
  '/owner/offerings/new': typeof OperatorOwnerOfferingsNewRoute
  '/owner/supply/$offeringRef': typeof OperatorOwnerSupplyOfferingRefRoute
  '/api/v1/market-operations/compare': typeof ApiV1MarketOperationsCompareRoute
  '/api/v1/market-operations/detail': typeof ApiV1MarketOperationsDetailRoute
  '/api/v1/market-operations/inspect-plan': typeof ApiV1MarketOperationsInspectPlanRoute
  '/api/v1/market-operations/search': typeof ApiV1MarketOperationsSearchRoute
  '/api/v1/operations/$invocationRef': typeof ApiV1OperationsInvocationRefRouteWithChildren
  '/api/v1/operations/call': typeof ApiV1OperationsCallRoute
  '/api/v1/services/$serviceId': typeof ApiV1ServicesServiceIdRoute
  '/api/v1/services/search': typeof ApiV1ServicesSearchRoute
  '/api/v1/operations/$invocationRef/cancel': typeof ApiV1OperationsInvocationRefCancelRoute
  '/api/v1/operations/$invocationRef/reconcile': typeof ApiV1OperationsInvocationRefReconcileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/engine': typeof EngineRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-providers': typeof ForProvidersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/ucp': typeof DotwellKnownUcpRoute
  '/activity': typeof OperatorActivityRoute
  '/agent-access': typeof OperatorAgentAccessRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/device_authorization': typeof OauthDevice_authorizationRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/operations/$operationRef': typeof OperationsOperationRefRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/t/new': typeof TNewRoute
  '/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/agent-access/authorize': typeof OperatorAgentAccessAuthorizeRoute
  '/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/owner/credit': typeof OperatorOwnerCreditRoute
  '/owner/offerings': typeof OperatorOwnerOfferingsRouteWithChildren
  '/owner/settings': typeof OperatorOwnerSettingsRoute
  '/owner/status': typeof OperatorOwnerStatusRoute
  '/owner/supply': typeof OperatorOwnerSupplyRouteWithChildren
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/anonymous': typeof ApiChatAnonymousRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/observability/client-error': typeof ApiObservabilityClientErrorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/market-metrics': typeof ApiV1MarketMetricsRoute
  '/api/v1/registry': typeof ApiV1RegistryRoute
  '/api/v1/release': typeof ApiV1ReleaseRoute
  '/api/v1/services': typeof ApiV1ServicesRouteWithChildren
  '/operations/invocations/$invocationRef': typeof OperationsInvocationsInvocationRefRoute
  '/owner/offerings/$offeringRef': typeof OperatorOwnerOfferingsOfferingRefRoute
  '/owner/offerings/new': typeof OperatorOwnerOfferingsNewRoute
  '/owner/supply/$offeringRef': typeof OperatorOwnerSupplyOfferingRefRoute
  '/api/v1/market-operations/compare': typeof ApiV1MarketOperationsCompareRoute
  '/api/v1/market-operations/detail': typeof ApiV1MarketOperationsDetailRoute
  '/api/v1/market-operations/inspect-plan': typeof ApiV1MarketOperationsInspectPlanRoute
  '/api/v1/market-operations/search': typeof ApiV1MarketOperationsSearchRoute
  '/api/v1/operations/$invocationRef': typeof ApiV1OperationsInvocationRefRouteWithChildren
  '/api/v1/operations/call': typeof ApiV1OperationsCallRoute
  '/api/v1/services/$serviceId': typeof ApiV1ServicesServiceIdRoute
  '/api/v1/services/search': typeof ApiV1ServicesSearchRoute
  '/api/v1/operations/$invocationRef/cancel': typeof ApiV1OperationsInvocationRefCancelRoute
  '/api/v1/operations/$invocationRef/reconcile': typeof ApiV1OperationsInvocationRefReconcileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/SKILL.md': typeof SKILLDotmdRoute
  '/_operator': typeof OperatorRouteWithChildren
  '/engine': typeof EngineRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-providers': typeof ForProvidersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/market': typeof MarketRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRouteWithChildren
  '/privacy': typeof PrivacyRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$slug/ucp': typeof SlugUcpRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/.well-known/ucp': typeof DotwellKnownUcpRoute
  '/_operator/activity': typeof OperatorActivityRoute
  '/_operator/agent-access': typeof OperatorAgentAccessRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/businesses': typeof ApiBusinessesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/device_authorization': typeof OauthDevice_authorizationRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/operations/$operationRef': typeof OperationsOperationRefRoute
  '/privacy/remove-business': typeof PrivacyRemoveBusinessRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/t/$threadId': typeof TThreadIdRoute
  '/t/new': typeof TNewRoute
  '/_operator/admin/audit-events': typeof OperatorAdminAuditEventsRoute
  '/_operator/admin/index-health': typeof OperatorAdminIndexHealthRoute
  '/_operator/agent-access/authorize': typeof OperatorAgentAccessAuthorizeRoute
  '/_operator/developers/discovery': typeof OperatorDevelopersDiscoveryRoute
  '/_operator/owner/credit': typeof OperatorOwnerCreditRoute
  '/_operator/owner/offerings': typeof OperatorOwnerOfferingsRouteWithChildren
  '/_operator/owner/settings': typeof OperatorOwnerSettingsRoute
  '/_operator/owner/status': typeof OperatorOwnerStatusRoute
  '/_operator/owner/supply': typeof OperatorOwnerSupplyRouteWithChildren
  '/api/businesses/$slug': typeof ApiBusinessesSlugRoute
  '/api/businesses/search': typeof ApiBusinessesSearchRoute
  '/api/chat/anonymous': typeof ApiChatAnonymousRoute
  '/api/discovery/examples': typeof ApiDiscoveryExamplesRoute
  '/api/discovery/schema': typeof ApiDiscoverySchemaRoute
  '/api/observability/client-error': typeof ApiObservabilityClientErrorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/market-metrics': typeof ApiV1MarketMetricsRoute
  '/api/v1/registry': typeof ApiV1RegistryRoute
  '/api/v1/release': typeof ApiV1ReleaseRoute
  '/api/v1/services': typeof ApiV1ServicesRouteWithChildren
  '/operations/invocations/$invocationRef': typeof OperationsInvocationsInvocationRefRoute
  '/_operator/owner/offerings/$offeringRef': typeof OperatorOwnerOfferingsOfferingRefRoute
  '/_operator/owner/offerings/new': typeof OperatorOwnerOfferingsNewRoute
  '/_operator/owner/supply/$offeringRef': typeof OperatorOwnerSupplyOfferingRefRoute
  '/api/v1/market-operations/compare': typeof ApiV1MarketOperationsCompareRoute
  '/api/v1/market-operations/detail': typeof ApiV1MarketOperationsDetailRoute
  '/api/v1/market-operations/inspect-plan': typeof ApiV1MarketOperationsInspectPlanRoute
  '/api/v1/market-operations/search': typeof ApiV1MarketOperationsSearchRoute
  '/api/v1/operations/$invocationRef': typeof ApiV1OperationsInvocationRefRouteWithChildren
  '/api/v1/operations/call': typeof ApiV1OperationsCallRoute
  '/api/v1/services/$serviceId': typeof ApiV1ServicesServiceIdRoute
  '/api/v1/services/search': typeof ApiV1ServicesSearchRoute
  '/api/v1/operations/$invocationRef/cancel': typeof ApiV1OperationsInvocationRefCancelRoute
  '/api/v1/operations/$invocationRef/reconcile': typeof ApiV1OperationsInvocationRefReconcileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/engine'
    | '/for-agents'
    | '/for-providers'
    | '/llms.txt'
    | '/market'
    | '/mcp'
    | '/operations'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/ucp'
    | '/activity'
    | '/agent-access'
    | '/api/$'
    | '/api/businesses'
    | '/api/health'
    | '/api/ready'
    | '/oauth/authorize'
    | '/oauth/device_authorization'
    | '/oauth/register'
    | '/oauth/token'
    | '/operations/$operationRef'
    | '/privacy/remove-business'
    | '/s/$shareToken'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/t/new'
    | '/admin/audit-events'
    | '/admin/index-health'
    | '/agent-access/authorize'
    | '/developers/discovery'
    | '/owner/credit'
    | '/owner/offerings'
    | '/owner/settings'
    | '/owner/status'
    | '/owner/supply'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/anonymous'
    | '/api/discovery/examples'
    | '/api/discovery/schema'
    | '/api/observability/client-error'
    | '/api/stripe/webhook'
    | '/api/v1/market-metrics'
    | '/api/v1/registry'
    | '/api/v1/release'
    | '/api/v1/services'
    | '/operations/invocations/$invocationRef'
    | '/owner/offerings/$offeringRef'
    | '/owner/offerings/new'
    | '/owner/supply/$offeringRef'
    | '/api/v1/market-operations/compare'
    | '/api/v1/market-operations/detail'
    | '/api/v1/market-operations/inspect-plan'
    | '/api/v1/market-operations/search'
    | '/api/v1/operations/$invocationRef'
    | '/api/v1/operations/call'
    | '/api/v1/services/$serviceId'
    | '/api/v1/services/search'
    | '/api/v1/operations/$invocationRef/cancel'
    | '/api/v1/operations/$invocationRef/reconcile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/engine'
    | '/for-agents'
    | '/for-providers'
    | '/llms.txt'
    | '/market'
    | '/mcp'
    | '/operations'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/ucp'
    | '/activity'
    | '/agent-access'
    | '/api/$'
    | '/api/businesses'
    | '/api/health'
    | '/api/ready'
    | '/oauth/authorize'
    | '/oauth/device_authorization'
    | '/oauth/register'
    | '/oauth/token'
    | '/operations/$operationRef'
    | '/privacy/remove-business'
    | '/s/$shareToken'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/t/new'
    | '/admin/audit-events'
    | '/admin/index-health'
    | '/agent-access/authorize'
    | '/developers/discovery'
    | '/owner/credit'
    | '/owner/offerings'
    | '/owner/settings'
    | '/owner/status'
    | '/owner/supply'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/anonymous'
    | '/api/discovery/examples'
    | '/api/discovery/schema'
    | '/api/observability/client-error'
    | '/api/stripe/webhook'
    | '/api/v1/market-metrics'
    | '/api/v1/registry'
    | '/api/v1/release'
    | '/api/v1/services'
    | '/operations/invocations/$invocationRef'
    | '/owner/offerings/$offeringRef'
    | '/owner/offerings/new'
    | '/owner/supply/$offeringRef'
    | '/api/v1/market-operations/compare'
    | '/api/v1/market-operations/detail'
    | '/api/v1/market-operations/inspect-plan'
    | '/api/v1/market-operations/search'
    | '/api/v1/operations/$invocationRef'
    | '/api/v1/operations/call'
    | '/api/v1/services/$serviceId'
    | '/api/v1/services/search'
    | '/api/v1/operations/$invocationRef/cancel'
    | '/api/v1/operations/$invocationRef/reconcile'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/SKILL.md'
    | '/_operator'
    | '/engine'
    | '/for-agents'
    | '/for-providers'
    | '/llms.txt'
    | '/market'
    | '/mcp'
    | '/operations'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$slug/ucp'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/ucp'
    | '/_operator/activity'
    | '/_operator/agent-access'
    | '/api/$'
    | '/api/businesses'
    | '/api/health'
    | '/api/ready'
    | '/oauth/authorize'
    | '/oauth/device_authorization'
    | '/oauth/register'
    | '/oauth/token'
    | '/operations/$operationRef'
    | '/privacy/remove-business'
    | '/s/$shareToken'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/t/$threadId'
    | '/t/new'
    | '/_operator/admin/audit-events'
    | '/_operator/admin/index-health'
    | '/_operator/agent-access/authorize'
    | '/_operator/developers/discovery'
    | '/_operator/owner/credit'
    | '/_operator/owner/offerings'
    | '/_operator/owner/settings'
    | '/_operator/owner/status'
    | '/_operator/owner/supply'
    | '/api/businesses/$slug'
    | '/api/businesses/search'
    | '/api/chat/anonymous'
    | '/api/discovery/examples'
    | '/api/discovery/schema'
    | '/api/observability/client-error'
    | '/api/stripe/webhook'
    | '/api/v1/market-metrics'
    | '/api/v1/registry'
    | '/api/v1/release'
    | '/api/v1/services'
    | '/operations/invocations/$invocationRef'
    | '/_operator/owner/offerings/$offeringRef'
    | '/_operator/owner/offerings/new'
    | '/_operator/owner/supply/$offeringRef'
    | '/api/v1/market-operations/compare'
    | '/api/v1/market-operations/detail'
    | '/api/v1/market-operations/inspect-plan'
    | '/api/v1/market-operations/search'
    | '/api/v1/operations/$invocationRef'
    | '/api/v1/operations/call'
    | '/api/v1/services/$serviceId'
    | '/api/v1/services/search'
    | '/api/v1/operations/$invocationRef/cancel'
    | '/api/v1/operations/$invocationRef/reconcile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  SKILLDotmdRoute: typeof SKILLDotmdRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  EngineRoute: typeof EngineRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForProvidersRoute: typeof ForProvidersRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MarketRoute: typeof MarketRoute
  McpRoute: typeof McpRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  PrivacyRoute: typeof PrivacyRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownHttpMessageSignaturesDirectoryRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  DotwellKnownUcpRoute: typeof DotwellKnownUcpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiBusinessesRoute: typeof ApiBusinessesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthDevice_authorizationRoute: typeof OauthDevice_authorizationRoute
  OauthRegisterRoute: typeof OauthRegisterRoute
  OauthTokenRoute: typeof OauthTokenRoute
  SShareTokenRoute: typeof SShareTokenRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TThreadIdRoute: typeof TThreadIdRoute
  TNewRoute: typeof TNewRoute
  ApiChatAnonymousRoute: typeof ApiChatAnonymousRoute
  ApiDiscoveryExamplesRoute: typeof ApiDiscoveryExamplesRoute
  ApiDiscoverySchemaRoute: typeof ApiDiscoverySchemaRoute
  ApiObservabilityClientErrorRoute: typeof ApiObservabilityClientErrorRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiV1MarketMetricsRoute: typeof ApiV1MarketMetricsRoute
  ApiV1RegistryRoute: typeof ApiV1RegistryRoute
  ApiV1ReleaseRoute: typeof ApiV1ReleaseRoute
  ApiV1ServicesRoute: typeof ApiV1ServicesRouteWithChildren
  ApiV1MarketOperationsCompareRoute: typeof ApiV1MarketOperationsCompareRoute
  ApiV1MarketOperationsDetailRoute: typeof ApiV1MarketOperationsDetailRoute
  ApiV1MarketOperationsInspectPlanRoute: typeof ApiV1MarketOperationsInspectPlanRoute
  ApiV1MarketOperationsSearchRoute: typeof ApiV1MarketOperationsSearchRoute
  ApiV1OperationsInvocationRefRoute: typeof ApiV1OperationsInvocationRefRouteWithChildren
  ApiV1OperationsCallRoute: typeof ApiV1OperationsCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator': {
      id: '/_operator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SKILL.md': {
      id: '/SKILL.md'
      path: '/SKILL.md'
      fullPath: '/SKILL.md'
      preLoaderRoute: typeof SKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/new': {
      id: '/t/new'
      path: '/t/new'
      fullPath: '/t/new'
      preLoaderRoute: typeof TNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$threadId': {
      id: '/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/t/$threadId'
      preLoaderRoute: typeof TThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareToken': {
      id: '/s/$shareToken'
      path: '/s/$shareToken'
      fullPath: '/s/$shareToken'
      preLoaderRoute: typeof SShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/remove-business': {
      id: '/privacy/remove-business'
      path: '/remove-business'
      fullPath: '/privacy/remove-business'
      preLoaderRoute: typeof PrivacyRemoveBusinessRouteImport
      parentRoute: typeof PrivacyRoute
    }
    '/operations/$operationRef': {
      id: '/operations/$operationRef'
      path: '/$operationRef'
      fullPath: '/operations/$operationRef'
      preLoaderRoute: typeof OperationsOperationRefRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/device_authorization': {
      id: '/oauth/device_authorization'
      path: '/oauth/device_authorization'
      fullPath: '/oauth/device_authorization'
      preLoaderRoute: typeof OauthDevice_authorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses': {
      id: '/api/businesses'
      path: '/api/businesses'
      fullPath: '/api/businesses'
      preLoaderRoute: typeof ApiBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/agent-access': {
      id: '/_operator/agent-access'
      path: '/agent-access'
      fullPath: '/agent-access'
      preLoaderRoute: typeof OperatorAgentAccessRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/activity': {
      id: '/_operator/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof OperatorActivityRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/.well-known/ucp': {
      id: '/.well-known/ucp'
      path: '/.well-known/ucp'
      fullPath: '/.well-known/ucp'
      preLoaderRoute: typeof DotwellKnownUcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/http-message-signatures-directory': {
      id: '/.well-known/http-message-signatures-directory'
      path: '/.well-known/http-message-signatures-directory'
      fullPath: '/.well-known/http-message-signatures-directory'
      preLoaderRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/ucp': {
      id: '/$slug/ucp'
      path: '/ucp'
      fullPath: '/$slug/ucp'
      preLoaderRoute: typeof SlugUcpRouteImport
      parentRoute: typeof SlugRoute
    }
    '/operations/invocations/$invocationRef': {
      id: '/operations/invocations/$invocationRef'
      path: '/invocations/$invocationRef'
      fullPath: '/operations/invocations/$invocationRef'
      preLoaderRoute: typeof OperationsInvocationsInvocationRefRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/api/v1/services': {
      id: '/api/v1/services'
      path: '/api/v1/services'
      fullPath: '/api/v1/services'
      preLoaderRoute: typeof ApiV1ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/release': {
      id: '/api/v1/release'
      path: '/api/v1/release'
      fullPath: '/api/v1/release'
      preLoaderRoute: typeof ApiV1ReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/registry': {
      id: '/api/v1/registry'
      path: '/api/v1/registry'
      fullPath: '/api/v1/registry'
      preLoaderRoute: typeof ApiV1RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/market-metrics': {
      id: '/api/v1/market-metrics'
      path: '/api/v1/market-metrics'
      fullPath: '/api/v1/market-metrics'
      preLoaderRoute: typeof ApiV1MarketMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/client-error': {
      id: '/api/observability/client-error'
      path: '/api/observability/client-error'
      fullPath: '/api/observability/client-error'
      preLoaderRoute: typeof ApiObservabilityClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/schema': {
      id: '/api/discovery/schema'
      path: '/api/discovery/schema'
      fullPath: '/api/discovery/schema'
      preLoaderRoute: typeof ApiDiscoverySchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/examples': {
      id: '/api/discovery/examples'
      path: '/api/discovery/examples'
      fullPath: '/api/discovery/examples'
      preLoaderRoute: typeof ApiDiscoveryExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/anonymous': {
      id: '/api/chat/anonymous'
      path: '/api/chat/anonymous'
      fullPath: '/api/chat/anonymous'
      preLoaderRoute: typeof ApiChatAnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses/search': {
      id: '/api/businesses/search'
      path: '/search'
      fullPath: '/api/businesses/search'
      preLoaderRoute: typeof ApiBusinessesSearchRouteImport
      parentRoute: typeof ApiBusinessesRoute
    }
    '/api/businesses/$slug': {
      id: '/api/businesses/$slug'
      path: '/$slug'
      fullPath: '/api/businesses/$slug'
      preLoaderRoute: typeof ApiBusinessesSlugRouteImport
      parentRoute: typeof ApiBusinessesRoute
    }
    '/_operator/owner/supply': {
      id: '/_operator/owner/supply'
      path: '/owner/supply'
      fullPath: '/owner/supply'
      preLoaderRoute: typeof OperatorOwnerSupplyRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/status': {
      id: '/_operator/owner/status'
      path: '/owner/status'
      fullPath: '/owner/status'
      preLoaderRoute: typeof OperatorOwnerStatusRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/settings': {
      id: '/_operator/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OperatorOwnerSettingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/offerings': {
      id: '/_operator/owner/offerings'
      path: '/owner/offerings'
      fullPath: '/owner/offerings'
      preLoaderRoute: typeof OperatorOwnerOfferingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/owner/credit': {
      id: '/_operator/owner/credit'
      path: '/owner/credit'
      fullPath: '/owner/credit'
      preLoaderRoute: typeof OperatorOwnerCreditRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/developers/discovery': {
      id: '/_operator/developers/discovery'
      path: '/developers/discovery'
      fullPath: '/developers/discovery'
      preLoaderRoute: typeof OperatorDevelopersDiscoveryRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/agent-access/authorize': {
      id: '/_operator/agent-access/authorize'
      path: '/authorize'
      fullPath: '/agent-access/authorize'
      preLoaderRoute: typeof OperatorAgentAccessAuthorizeRouteImport
      parentRoute: typeof OperatorAgentAccessRoute
    }
    '/_operator/admin/index-health': {
      id: '/_operator/admin/index-health'
      path: '/admin/index-health'
      fullPath: '/admin/index-health'
      preLoaderRoute: typeof OperatorAdminIndexHealthRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/_operator/admin/audit-events': {
      id: '/_operator/admin/audit-events'
      path: '/admin/audit-events'
      fullPath: '/admin/audit-events'
      preLoaderRoute: typeof OperatorAdminAuditEventsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/api/v1/services/search': {
      id: '/api/v1/services/search'
      path: '/search'
      fullPath: '/api/v1/services/search'
      preLoaderRoute: typeof ApiV1ServicesSearchRouteImport
      parentRoute: typeof ApiV1ServicesRoute
    }
    '/api/v1/services/$serviceId': {
      id: '/api/v1/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/api/v1/services/$serviceId'
      preLoaderRoute: typeof ApiV1ServicesServiceIdRouteImport
      parentRoute: typeof ApiV1ServicesRoute
    }
    '/api/v1/operations/call': {
      id: '/api/v1/operations/call'
      path: '/api/v1/operations/call'
      fullPath: '/api/v1/operations/call'
      preLoaderRoute: typeof ApiV1OperationsCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/operations/$invocationRef': {
      id: '/api/v1/operations/$invocationRef'
      path: '/api/v1/operations/$invocationRef'
      fullPath: '/api/v1/operations/$invocationRef'
      preLoaderRoute: typeof ApiV1OperationsInvocationRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/market-operations/search': {
      id: '/api/v1/market-operations/search'
      path: '/api/v1/market-operations/search'
      fullPath: '/api/v1/market-operations/search'
      preLoaderRoute: typeof ApiV1MarketOperationsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/market-operations/inspect-plan': {
      id: '/api/v1/market-operations/inspect-plan'
      path: '/api/v1/market-operations/inspect-plan'
      fullPath: '/api/v1/market-operations/inspect-plan'
      preLoaderRoute: typeof ApiV1MarketOperationsInspectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/market-operations/detail': {
      id: '/api/v1/market-operations/detail'
      path: '/api/v1/market-operations/detail'
      fullPath: '/api/v1/market-operations/detail'
      preLoaderRoute: typeof ApiV1MarketOperationsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/market-operations/compare': {
      id: '/api/v1/market-operations/compare'
      path: '/api/v1/market-operations/compare'
      fullPath: '/api/v1/market-operations/compare'
      preLoaderRoute: typeof ApiV1MarketOperationsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_operator/owner/supply/$offeringRef': {
      id: '/_operator/owner/supply/$offeringRef'
      path: '/$offeringRef'
      fullPath: '/owner/supply/$offeringRef'
      preLoaderRoute: typeof OperatorOwnerSupplyOfferingRefRouteImport
      parentRoute: typeof OperatorOwnerSupplyRoute
    }
    '/_operator/owner/offerings/new': {
      id: '/_operator/owner/offerings/new'
      path: '/new'
      fullPath: '/owner/offerings/new'
      preLoaderRoute: typeof OperatorOwnerOfferingsNewRouteImport
      parentRoute: typeof OperatorOwnerOfferingsRoute
    }
    '/_operator/owner/offerings/$offeringRef': {
      id: '/_operator/owner/offerings/$offeringRef'
      path: '/$offeringRef'
      fullPath: '/owner/offerings/$offeringRef'
      preLoaderRoute: typeof OperatorOwnerOfferingsOfferingRefRouteImport
      parentRoute: typeof OperatorOwnerOfferingsRoute
    }
    '/api/v1/operations/$invocationRef/reconcile': {
      id: '/api/v1/operations/$invocationRef/reconcile'
      path: '/reconcile'
      fullPath: '/api/v1/operations/$invocationRef/reconcile'
      preLoaderRoute: typeof ApiV1OperationsInvocationRefReconcileRouteImport
      parentRoute: typeof ApiV1OperationsInvocationRefRoute
    }
    '/api/v1/operations/$invocationRef/cancel': {
      id: '/api/v1/operations/$invocationRef/cancel'
      path: '/cancel'
      fullPath: '/api/v1/operations/$invocationRef/cancel'
      preLoaderRoute: typeof ApiV1OperationsInvocationRefCancelRouteImport
      parentRoute: typeof ApiV1OperationsInvocationRefRoute
    }
  }
}

interface SlugRouteChildren {
  SlugUcpRoute: typeof SlugUcpRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugUcpRoute: SlugUcpRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface OperatorAgentAccessRouteChildren {
  OperatorAgentAccessAuthorizeRoute: typeof OperatorAgentAccessAuthorizeRoute
}

const OperatorAgentAccessRouteChildren: OperatorAgentAccessRouteChildren = {
  OperatorAgentAccessAuthorizeRoute: OperatorAgentAccessAuthorizeRoute,
}

const OperatorAgentAccessRouteWithChildren =
  OperatorAgentAccessRoute._addFileChildren(OperatorAgentAccessRouteChildren)

interface OperatorOwnerOfferingsRouteChildren {
  OperatorOwnerOfferingsOfferingRefRoute: typeof OperatorOwnerOfferingsOfferingRefRoute
  OperatorOwnerOfferingsNewRoute: typeof OperatorOwnerOfferingsNewRoute
}

const OperatorOwnerOfferingsRouteChildren: OperatorOwnerOfferingsRouteChildren =
  {
    OperatorOwnerOfferingsOfferingRefRoute:
      OperatorOwnerOfferingsOfferingRefRoute,
    OperatorOwnerOfferingsNewRoute: OperatorOwnerOfferingsNewRoute,
  }

const OperatorOwnerOfferingsRouteWithChildren =
  OperatorOwnerOfferingsRoute._addFileChildren(
    OperatorOwnerOfferingsRouteChildren,
  )

interface OperatorOwnerSupplyRouteChildren {
  OperatorOwnerSupplyOfferingRefRoute: typeof OperatorOwnerSupplyOfferingRefRoute
}

const OperatorOwnerSupplyRouteChildren: OperatorOwnerSupplyRouteChildren = {
  OperatorOwnerSupplyOfferingRefRoute: OperatorOwnerSupplyOfferingRefRoute,
}

const OperatorOwnerSupplyRouteWithChildren =
  OperatorOwnerSupplyRoute._addFileChildren(OperatorOwnerSupplyRouteChildren)

interface OperatorRouteChildren {
  OperatorActivityRoute: typeof OperatorActivityRoute
  OperatorAgentAccessRoute: typeof OperatorAgentAccessRouteWithChildren
  OperatorAdminAuditEventsRoute: typeof OperatorAdminAuditEventsRoute
  OperatorAdminIndexHealthRoute: typeof OperatorAdminIndexHealthRoute
  OperatorDevelopersDiscoveryRoute: typeof OperatorDevelopersDiscoveryRoute
  OperatorOwnerCreditRoute: typeof OperatorOwnerCreditRoute
  OperatorOwnerOfferingsRoute: typeof OperatorOwnerOfferingsRouteWithChildren
  OperatorOwnerSettingsRoute: typeof OperatorOwnerSettingsRoute
  OperatorOwnerStatusRoute: typeof OperatorOwnerStatusRoute
  OperatorOwnerSupplyRoute: typeof OperatorOwnerSupplyRouteWithChildren
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorActivityRoute: OperatorActivityRoute,
  OperatorAgentAccessRoute: OperatorAgentAccessRouteWithChildren,
  OperatorAdminAuditEventsRoute: OperatorAdminAuditEventsRoute,
  OperatorAdminIndexHealthRoute: OperatorAdminIndexHealthRoute,
  OperatorDevelopersDiscoveryRoute: OperatorDevelopersDiscoveryRoute,
  OperatorOwnerCreditRoute: OperatorOwnerCreditRoute,
  OperatorOwnerOfferingsRoute: OperatorOwnerOfferingsRouteWithChildren,
  OperatorOwnerSettingsRoute: OperatorOwnerSettingsRoute,
  OperatorOwnerStatusRoute: OperatorOwnerStatusRoute,
  OperatorOwnerSupplyRoute: OperatorOwnerSupplyRouteWithChildren,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface OperationsRouteChildren {
  OperationsOperationRefRoute: typeof OperationsOperationRefRoute
  OperationsInvocationsInvocationRefRoute: typeof OperationsInvocationsInvocationRefRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsOperationRefRoute: OperationsOperationRefRoute,
  OperationsInvocationsInvocationRefRoute:
    OperationsInvocationsInvocationRefRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface PrivacyRouteChildren {
  PrivacyRemoveBusinessRoute: typeof PrivacyRemoveBusinessRoute
}

const PrivacyRouteChildren: PrivacyRouteChildren = {
  PrivacyRemoveBusinessRoute: PrivacyRemoveBusinessRoute,
}

const PrivacyRouteWithChildren =
  PrivacyRoute._addFileChildren(PrivacyRouteChildren)

interface ApiBusinessesRouteChildren {
  ApiBusinessesSlugRoute: typeof ApiBusinessesSlugRoute
  ApiBusinessesSearchRoute: typeof ApiBusinessesSearchRoute
}

const ApiBusinessesRouteChildren: ApiBusinessesRouteChildren = {
  ApiBusinessesSlugRoute: ApiBusinessesSlugRoute,
  ApiBusinessesSearchRoute: ApiBusinessesSearchRoute,
}

const ApiBusinessesRouteWithChildren = ApiBusinessesRoute._addFileChildren(
  ApiBusinessesRouteChildren,
)

interface ApiV1ServicesRouteChildren {
  ApiV1ServicesServiceIdRoute: typeof ApiV1ServicesServiceIdRoute
  ApiV1ServicesSearchRoute: typeof ApiV1ServicesSearchRoute
}

const ApiV1ServicesRouteChildren: ApiV1ServicesRouteChildren = {
  ApiV1ServicesServiceIdRoute: ApiV1ServicesServiceIdRoute,
  ApiV1ServicesSearchRoute: ApiV1ServicesSearchRoute,
}

const ApiV1ServicesRouteWithChildren = ApiV1ServicesRoute._addFileChildren(
  ApiV1ServicesRouteChildren,
)

interface ApiV1OperationsInvocationRefRouteChildren {
  ApiV1OperationsInvocationRefCancelRoute: typeof ApiV1OperationsInvocationRefCancelRoute
  ApiV1OperationsInvocationRefReconcileRoute: typeof ApiV1OperationsInvocationRefReconcileRoute
}

const ApiV1OperationsInvocationRefRouteChildren: ApiV1OperationsInvocationRefRouteChildren =
  {
    ApiV1OperationsInvocationRefCancelRoute:
      ApiV1OperationsInvocationRefCancelRoute,
    ApiV1OperationsInvocationRefReconcileRoute:
      ApiV1OperationsInvocationRefReconcileRoute,
  }

const ApiV1OperationsInvocationRefRouteWithChildren =
  ApiV1OperationsInvocationRefRoute._addFileChildren(
    ApiV1OperationsInvocationRefRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  SKILLDotmdRoute: SKILLDotmdRoute,
  OperatorRoute: OperatorRouteWithChildren,
  EngineRoute: EngineRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForProvidersRoute: ForProvidersRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MarketRoute: MarketRoute,
  McpRoute: McpRoute,
  OperationsRoute: OperationsRouteWithChildren,
  PrivacyRoute: PrivacyRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DotwellKnownHttpMessageSignaturesDirectoryRoute:
    DotwellKnownHttpMessageSignaturesDirectoryRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  DotwellKnownUcpRoute: DotwellKnownUcpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiBusinessesRoute: ApiBusinessesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthDevice_authorizationRoute: OauthDevice_authorizationRoute,
  OauthRegisterRoute: OauthRegisterRoute,
  OauthTokenRoute: OauthTokenRoute,
  SShareTokenRoute: SShareTokenRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TThreadIdRoute: TThreadIdRoute,
  TNewRoute: TNewRoute,
  ApiChatAnonymousRoute: ApiChatAnonymousRoute,
  ApiDiscoveryExamplesRoute: ApiDiscoveryExamplesRoute,
  ApiDiscoverySchemaRoute: ApiDiscoverySchemaRoute,
  ApiObservabilityClientErrorRoute: ApiObservabilityClientErrorRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiV1MarketMetricsRoute: ApiV1MarketMetricsRoute,
  ApiV1RegistryRoute: ApiV1RegistryRoute,
  ApiV1ReleaseRoute: ApiV1ReleaseRoute,
  ApiV1ServicesRoute: ApiV1ServicesRouteWithChildren,
  ApiV1MarketOperationsCompareRoute: ApiV1MarketOperationsCompareRoute,
  ApiV1MarketOperationsDetailRoute: ApiV1MarketOperationsDetailRoute,
  ApiV1MarketOperationsInspectPlanRoute: ApiV1MarketOperationsInspectPlanRoute,
  ApiV1MarketOperationsSearchRoute: ApiV1MarketOperationsSearchRoute,
  ApiV1OperationsInvocationRefRoute:
    ApiV1OperationsInvocationRefRouteWithChildren,
  ApiV1OperationsCallRoute: ApiV1OperationsCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
