import { defineTable } from 'convex/server'
import { v } from 'convex/values'

const currency = v.string()
const exponent = v.number()
const units = v.string()
const identifier = v.string()
const evidenceRefs = v.array(v.string())
export const commercialPolicyControlValue = v.union(
  v.object({
    family: v.literal('commercial_perimeter'),
    sellerModel: v.literal('principal_reseller'),
    customerSegment: v.literal('business_only'),
    customerCryptoEntitlement: v.literal(false),
  }),
  v.object({
    family: v.literal('tax'),
    serviceFeeTaxBps: v.number(),
    taxInvoiceIssuance: v.union(
      v.literal('disabled_pending_approval'),
      v.literal('enabled'),
    ),
  }),
  v.object({
    family: v.literal('accounting_client_money'),
    minimumFundingPrincipalUnits: units,
    maximumFundingPrincipalUnits: units,
    fundingIncrementUnits: units,
    legalCustomerMaximumAccessibleUnits: units,
    balanceClassification: v.literal('customer_contract_liability'),
  }),
  v.object({
    family: v.literal('privacy_retention'),
    evidenceRetentionDays: v.number(),
    legalHoldSupported: v.literal(true),
  }),
  v.object({
    family: v.literal('treasury_custody'),
    treasuryAsset: v.literal('USDC'),
    treasuryExponent: v.literal(6),
    minimumBufferUnits: units,
    ledgerAuthority: v.literal('formance_community'),
    formanceLedgerVersion: v.string(),
    formanceGatewayVersion: v.string(),
    formanceSchemaVersion: v.string(),
    maximumSdkIntegerUnits: units,
    architectureReviewCumulativeUnits: units,
    deploymentClass: v.union(
      v.literal('local_ci'),
      v.literal('synthetic_vps_fixture'),
      v.literal('real_money'),
    ),
    postgresProtection: v.union(
      v.literal('disposable_fixture'),
      v.literal('managed_pitr'),
    ),
    recoveryPointObjectiveMinutes: v.number(),
    recoveryTimeObjectiveMinutes: v.number(),
  }),
  v.object({
    family: v.literal('operations'),
    fundingServiceFeeBps: v.number(),
    buyerPricingMarginBps: v.number(),
    commitmentTtlMs: v.number(),
    formanceSdkVersion: v.string(),
    formanceSdkArtifactDigest: v.string(),
    backupControl: v.union(
      v.literal('disposable_fixture'),
      v.literal('postgres_pitr'),
    ),
    restoreControl: v.union(
      v.literal('disposable_rehearsed'),
      v.literal('production_rehearsed'),
    ),
    dailyCloseControl: v.union(
      v.literal('not_required_fixture'),
      v.literal('human_signed'),
    ),
  }),
)
export const x402PaymentAuthorizationFailureCodeValue = v.union(
  v.literal('custody_configuration_invalid'),
  v.literal('request_fingerprint_context_invalid'),
  v.literal('material_unavailable'),
  v.literal('material_identity_invalid'),
  v.literal('external_spend_identity_invalid'),
  v.literal('provider_authority_invalid'),
  v.literal('grant_invalid'),
  v.literal('managed_authorization_unavailable'),
)
export const x402PaymentAuthorizationFailureDetailValue = v.union(
  v.literal('not_found'),
  v.literal('inactive'),
  v.literal('stale_generation'),
  v.literal('expired'),
  v.literal('digest_mismatch'),
  v.literal('credential_unavailable'),
  v.literal('lease_not_found'),
  v.literal('lease_inactive'),
  v.literal('lease_expired'),
  v.literal('lease_generation_stale'),
  v.literal('lease_digest_stale'),
  v.literal('lease_scope_mismatch'),
  v.literal('lease_resource_mismatch'),
  v.literal('lease_identity_mismatch'),
  v.literal('connection_not_found'),
  v.literal('connection_inactive'),
  v.literal('connection_expired'),
  v.literal('readiness_expired'),
  v.literal('readiness_mismatch'),
  v.literal('authority_read_failed'),
)
export const moneyTables = {
  moneyCommercialPolicies: defineTable({
    policyRef: identifier,
    family: v.union(
      v.literal('commercial_perimeter'),
      v.literal('tax'),
      v.literal('accounting_client_money'),
      v.literal('privacy_retention'),
      v.literal('treasury_custody'),
      v.literal('operations'),
    ),
    environment: v.union(v.literal('sandbox'), v.literal('production')),
    revision: v.number(),
    lifecycle: v.union(
      v.literal('active'),
      v.literal('superseded'),
      v.literal('suspended'),
    ),
    effectiveAt: v.number(),
    expiresAt: v.number(),
    evidenceRef: identifier,
    evidenceDigest: identifier,
    control: commercialPolicyControlValue,
    approvedByPrincipalRef: identifier,
    activeAccountRef: identifier,
    authorityGeneration: v.number(),
    correlationRef: identifier,
    idempotencyRef: identifier,
    commandDigest: identifier,
    activatedAt: v.number(),
    supersededByPolicyRef: v.optional(identifier),
    suspendedAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index('by_policyRef', ['policyRef'])
    .index('by_environment_and_family_and_lifecycle', [
      'environment',
      'family',
      'lifecycle',
    ]),
  moneyReconciliationCases: defineTable({
    caseRef: identifier,
    accountRef: identifier,
    kind: v.union(
      v.literal('projection_mismatch'),
      v.literal('processor_difference'),
      v.literal('treasury_difference'),
      v.literal('settlement_difference'),
      v.literal('document_difference'),
    ),
    status: v.union(v.literal('open'), v.literal('resolved')),
    scopeType: v.optional(v.union(
      v.literal('account'),
      v.literal('legal_customer'),
      v.literal('treasury_pool'),
      v.literal('operation'),
      v.literal('provider_obligation'),
      v.literal('document'),
    )),
    scopeRef: v.optional(identifier),
    ownerPrincipalRef: v.optional(identifier),
    transactionRef: v.optional(identifier),
    reasonCode: identifier,
    evidenceRefs,
    resolutionEvidenceRefs: v.optional(evidenceRefs),
    createdAt: v.number(),
    updatedAt: v.number(),
    resolvedAt: v.optional(v.number()),
  })
    .index('by_caseRef', ['caseRef'])
    .index('by_accountRef_and_createdAt', ['accountRef', 'createdAt'])
    .index('by_accountRef_and_status_and_createdAt', ['accountRef', 'status', 'createdAt'])
    .index('by_scopeType_and_scopeRef_and_status', ['scopeType', 'scopeRef', 'status']),
  moneyDocuments: defineTable({
    documentRef: identifier,
    accountRef: identifier,
    kind: v.union(
      v.literal('funding_receipt'),
      v.literal('service_fee_document'),
      v.literal('statement'),
      v.literal('daily_close'),
      v.literal('adjustment'),
      v.literal('tax_invoice'),
    ),
    sourceTransactionRefs: evidenceRefs,
    amountUnits: units,
    residualUnits: units,
    policyRefs: evidenceRefs,
    policyDigest: identifier,
    templateVersion: identifier,
    renderInputJson: v.string(),
    renderInputDigest: identifier,
    state: v.union(
      v.literal('building'),
      v.literal('adjusting'),
      v.literal('rendering'),
      v.literal('awaiting_signature'),
      v.literal('issued'),
      v.literal('failed'),
    ),
    environment: v.union(v.literal('sandbox'), v.literal('production')),
    sourceCount: v.number(),
    snapshotDigest: identifier,
    snapshotCutoffAt: v.optional(v.number()),
    periodStart: v.optional(v.number()),
    periodEnd: v.optional(v.number()),
    nextCursor: v.optional(v.string()),
    pageCount: v.optional(v.number()),
    exactAmountUnits: v.optional(units),
    workId: v.optional(identifier),
    failureCode: v.optional(identifier),
    fileId: v.optional(v.id('_storage')),
    fileDigest: v.optional(identifier),
    csvFileId: v.optional(v.id('_storage')),
    csvFileDigest: v.optional(identifier),
    renderedAt: v.optional(v.number()),
    signedByPrincipalRef: v.optional(identifier),
    signedAt: v.optional(v.number()),
    closeEvidenceDigest: v.optional(identifier),
    createdAt: v.number(),
  })
    .index('by_documentRef', ['documentRef'])
    .index('by_accountRef_and_createdAt', ['accountRef', 'createdAt']),
  moneyDocumentSnapshotPages: defineTable({
    pageRef: identifier,
    documentRef: identifier,
    accountRef: identifier,
    position: v.number(),
    transactionRefs: evidenceRefs,
    exactAmountUnits: units,
    pageDigest: identifier,
    createdAt: v.number(),
  })
    .index('by_pageRef', ['pageRef'])
    .index('by_documentRef_and_position', ['documentRef', 'position']),
  moneyFundingCommands: defineTable({
    commandRef: identifier,
    accountRef: identifier,
    legalCustomerRef: identifier,
    actorPrincipalRef: identifier,
    environment: v.union(v.literal('sandbox'), v.literal('production')),
    currency: v.literal('AUD'),
    exponent: v.literal(6),
    principalUnits: units,
    serviceFeeUnits: units,
    taxUnits: units,
    totalUnits: units,
    commercialPolicyDigest: identifier,
    commercialPolicyRefs: evidenceRefs,
    idempotencyKey: identifier,
    inputDigest: identifier,
    successReturnRef: identifier,
    providerRecoveryDeadlineAt: v.number(),
    state: v.union(
      v.literal('pending'),
      v.literal('succeeded'),
      v.literal('failed'),
      v.literal('outcome_unknown'),
    ),
    externalRef: v.optional(identifier),
    providerStatus: v.optional(v.union(
      v.literal('pending'),
      v.literal('succeeded'),
      v.literal('failed'),
      v.literal('outcome_unknown'),
    )),
    providerEvidenceRef: v.optional(identifier),
    requestDigest: v.optional(identifier),
    metadataDigest: v.optional(identifier),
    checkoutSessionDigest: v.optional(identifier),
    paymentIntentDigest: v.optional(identifier),
    evidenceDigest: v.optional(identifier),
    paymentId: v.optional(identifier),
    appliedStripeEventId: v.optional(identifier),
    appliedPayloadDigest: v.optional(identifier),
    appliedTransactionRef: v.optional(identifier),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_commandRef', ['commandRef'])
    .index('by_idempotencyKey', ['idempotencyKey'])
    .index('by_externalRef', ['externalRef'])
    .index('by_accountRef_and_createdAt', ['accountRef', 'createdAt'])
    .index('by_accountRef_and_state', ['accountRef', 'state'])
    .index('by_legalCustomerRef_and_state', ['legalCustomerRef', 'state']),
  moneyLegalCustomerBindings: defineTable({
    accountRef: identifier,
    legalCustomerRef: identifier,
    ownershipRef: identifier,
    accountRevision: v.number(),
    ownershipRevision: v.number(),
    state: v.union(v.literal('active'), v.literal('locked')),
    version: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_accountRef', ['accountRef'])
    .index('by_legalCustomerRef_and_state', ['legalCustomerRef', 'state']),
  moneyTreasuryObservations: defineTable({
    observationRef: identifier,
    environment: v.union(v.literal('sandbox'), v.literal('production')),
    custodyRef: identifier,
    custodyGeneration: v.number(),
    network: identifier,
    asset: v.literal('USDC'),
    exponent: v.literal(6),
    totalUnits: units,
    bufferUnits: units,
    evidenceRef: identifier,
    evidenceDigest: identifier,
    observedAt: v.number(),
    recordedAt: v.number(),
  })
    .index('by_observationRef', ['observationRef'])
    .index('by_environment_and_observedAt', ['environment', 'observedAt'])
    .index('by_custody_and_observedAt', [
      'environment',
      'custodyRef',
      'custodyGeneration',
      'observedAt',
    ]),
  moneyProviderObligations: defineTable({
    obligationRef: identifier,
    invocationRef: identifier,
    operationRef: identifier,
    providerRef: identifier,
    buyerAccountRef: identifier,
    buyerAsset: v.literal('AUD'),
    buyerExponent: v.literal(6),
    buyerAmountUnits: units,
    providerAsset: v.literal('USDC'),
    providerExponent: v.literal(6),
    providerAmountUnits: units,
    settlementMethod: v.literal('managed_x402'),
    state: v.union(
      v.literal('accrued'),
      v.literal('held'),
      v.literal('settled'),
      v.literal('reversed'),
      v.literal('disputed'),
    ),
    payoutEligibility: v.literal('ineligible_x402'),
    evidenceRefs,
    createdAt: v.number(),
    updatedAt: v.number(),
    settledAt: v.optional(v.number()),
  })
    .index('by_obligationRef', ['obligationRef'])
    .index('by_invocationRef', ['invocationRef'])
    .index('by_buyerAccountRef_and_createdAt', ['buyerAccountRef', 'createdAt'])
    .index('by_providerRef_and_createdAt', ['providerRef', 'createdAt']),
  moneyUsageEvents: defineTable({
    usageRef: identifier,
    principalId: identifier,
    accountId: v.optional(identifier),
    credentialId: identifier,
    currency,
    exponent,
    serviceRef: identifier,
    offeringRef: identifier,
    businessId: identifier,
    invocationRef: identifier,
    attemptRef: identifier,
    operationKey: identifier,
    priceDigest: identifier,
    chargeState: v.union(v.literal('free_tier'), v.literal('paid'), v.literal('insufficient_credit'), v.literal('outcome_unknown'), v.literal('refunded')),
    amountUnits: units,
    transactionRef: v.optional(identifier),
    observedAt: v.number(),
  })
    .index('by_principalId_and_credentialId_and_currency_and_observedAt', ['principalId', 'credentialId', 'currency', 'observedAt'])
    .index('by_businessId_and_observedAt', ['businessId', 'observedAt'])
    .index('by_invocationRef', ['invocationRef'])
    .index('by_usageRef', ['usageRef']),
  moneyX402PaymentAttempts: defineTable({
    dispatchRef: identifier,
    attemptRef: identifier,
    effectGeneration: v.number(),
    operationRef: v.optional(identifier),
    inputDigest: v.optional(identifier),
    paymentIdentifier: identifier,
    operationKeyDigest: identifier,
    challengeDigest: identifier,
    challengeJson: v.string(),
    selectedRequirementJson: v.string(),
    providerEndpoint: v.string(),
    credentialRef: identifier,
    scheme: v.string(),
    network: v.string(),
    asset: v.string(),
    payTo: v.string(),
    amountUnits: units,
    currency,
    exponent,
    custodyRef: identifier,
    custodyBudgetRef: v.optional(identifier),
    custodyGeneration: v.optional(v.number()),
    custodyDailyMaximumUnits: v.optional(units),
    authorizationDigest: identifier,
    reservationRef: v.optional(identifier),
    paymentIdentityDigest: v.optional(identifier),
    paymentSignatureDigest: v.optional(identifier),
    requestFingerprint: v.optional(identifier),
    paymentUnsignedMaterialJson: v.optional(v.string()),
    paymentUnsignedMaterialDigest: v.optional(identifier),
    paymentSigningIdempotencyKey: v.optional(v.string()),
    paymentPayer: v.optional(v.string()),
    paymentNonce: v.optional(v.string()),
    paymentAuthorizationValidBefore: v.optional(v.string()),
    paymentAuthorizationExpiresAt: v.optional(v.number()),
    paymentSigningClaimedAt: v.optional(v.number()),
    // Non-secret, bounded explanation for a managed authorization that stopped
    // before a payment header was available. This survives the later unpaid
    // observation so operators do not have to infer the failed transition.
    authorizationFailureCode: v.optional(x402PaymentAuthorizationFailureCodeValue),
    authorizationFailureDetail: v.optional(x402PaymentAuthorizationFailureDetailValue),
    authorizationFailureObservedAt: v.optional(v.number()),
    state: v.union(
      v.literal('prepared'),
      v.literal('possibly_submitted'),
      v.literal('observed'),
      v.literal('reconciliation_required'),
    ),
    preparedAt: v.number(),
    submissionStartedAt: v.optional(v.number()),
    observedAt: v.optional(v.number()),
    transportObservationDigest: v.optional(identifier),
    transportRequestDigest: v.optional(identifier),
    paymentObservationDigest: v.optional(identifier),
    settlementStatus: v.optional(v.union(
      v.literal('settled'),
      v.literal('not_settled'),
      v.literal('unknown'),
    )),
    paymentResponseDigest: v.optional(identifier),
    quarantinedResponseDigest: v.optional(identifier),
    quarantinedOutputJson: v.optional(v.string()),
    reconciliationEvidenceRef: v.optional(identifier),
    reconciliationEvidenceDigest: v.optional(identifier),
    evidenceRefs,
  })
    .index('by_attemptRef_and_effectGeneration', ['attemptRef', 'effectGeneration'])
    .index('by_custodyRef', ['custodyRef'])
    .index('by_authorizationDigest', ['authorizationDigest'])
    .index('by_paymentIdentifier', ['paymentIdentifier'])
    .index('by_state_and_paymentAuthorizationExpiresAt', ['state', 'paymentAuthorizationExpiresAt']),
  moneyCredentialUsageSummaries: defineTable({
    principalId: identifier,
    credentialId: identifier,
    currency,
    exponent,
    callCount: v.number(),
    paidCallCount: v.number(),
    freeCallCount: v.number(),
    grossSpendUnits: units,
    states: v.array(v.union(v.literal('free_tier'), v.literal('paid'), v.literal('insufficient_credit'), v.literal('outcome_unknown'), v.literal('refunded'))),
    updatedAt: v.number(),
  }).index('by_principalId_and_credentialId_and_currency', ['principalId', 'credentialId', 'currency']),
  /**
   * ADR-034 delivery evidence. Insert-once and never updated: the money ledger
   * remains the economic authority and Action Invocation the lifecycle
   * authority, so corrections append facts elsewhere.
   */
  qualifiedUseReceipts: defineTable({
    qualifiedUseRef: identifier,
    materialDigest: identifier,
    invocationRef: identifier,
    attemptRef: identifier,
    effectGeneration: v.number(),
    businessId: identifier,
    /** Canonical Phase-1 authority pinned when the receipt is admitted. */
    owningAccountRef: v.optional(identifier),
    authorityPrincipalRef: v.optional(identifier),
    authorityGrantRef: v.optional(identifier),
    authorityGrantGeneration: v.optional(v.number()),
    authorityResourceRef: v.optional(identifier),
    operationRef: identifier,
    publicationRef: identifier,
    publicationRevision: v.number(),
    contractDigest: identifier,
    bindingDigest: identifier,
    principalClass: v.union(v.literal('agent_key'), v.literal('human_owner'), v.literal('service')),
    requestDigest: identifier,
    responseDigest: identifier,
    evidenceRefs,
    environment: v.literal('production'),
    qualifiedAt: v.number(),
    usageRef: v.optional(identifier),
    transactionRef: v.optional(identifier),
  })
    .index('by_qualifiedUseRef', ['qualifiedUseRef'])
    .index('by_businessId_and_qualifiedAt', ['businessId', 'qualifiedAt'])
    .index('by_invocationRef', ['invocationRef'])
    .index('by_operationRef_and_qualifiedAt', ['operationRef', 'qualifiedAt']),
  moneyConnectAccountCommands: defineTable({
    commandRef: identifier,
    businessId: identifier,
    currency,
    exponent,
    idempotencyKey: identifier,
    inputDigest: identifier,
    providerRequestDigest: identifier,
    providerRecoveryDeadlineAt: v.number(),
    recoveryLeaseGeneration: v.number(),
    recoveryLeaseOwner: v.optional(identifier),
    recoveryLeaseExpiresAt: v.optional(v.number()),
    state: v.union(v.literal('pending'), v.literal('succeeded'), v.literal('failed'), v.literal('outcome_unknown')),
    stripeAccountId: v.optional(identifier),
    providerEvidenceRef: v.optional(identifier),
    failureCode: v.optional(identifier),
    failureRetryable: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_commandRef', ['commandRef'])
    .index('by_businessId_and_currency', ['businessId', 'currency'])
    .index('by_businessId_and_currency_and_idempotencyKey', ['businessId', 'currency', 'idempotencyKey'])
    .index('by_idempotencyKey', ['idempotencyKey']),
  moneyStripeEvents: defineTable({
    stripeEventId: identifier,
    eventType: identifier,
    payloadDigest: identifier,
    commandRef: v.optional(identifier),
    providerObjectId: identifier,
    providerObjectDigest: v.optional(identifier),
    providerObjectVersion: v.optional(v.number()),
    sessionId: v.optional(identifier),
    paymentId: v.optional(identifier),
    paymentIntentDigest: v.optional(identifier),
    checkoutStatus: v.optional(v.union(v.literal('paid'), v.literal('failed'), v.literal('expired'))),
    currency: v.optional(currency),
    amountUnits: v.optional(units),
    exponent: v.optional(exponent),
    metadataDigest: v.optional(identifier),
    status: v.union(v.literal('received'), v.literal('applied'), v.literal('ignored'), v.literal('failed')),
    appliedRef: v.optional(identifier),
    receivedAt: v.number(),
    appliedAt: v.optional(v.number()),
  }).index('by_stripeEventId', ['stripeEventId']),
  moneyPayoutAccounts: defineTable({
    businessId: identifier,
    currency,
    exponent,
    stripeAccountId: identifier,
    state: v.union(v.literal('not_started'), v.literal('onboarding_started'), v.literal('submitted'), v.literal('restricted'), v.literal('ready')),
    detailsSubmitted: v.boolean(),
    recipientCapabilityActive: v.boolean(),
    requirementsDigest: identifier,
    lastStripeEventId: v.optional(identifier),
    lastStripePayloadDigest: v.optional(identifier),
    providerObjectDigest: v.optional(identifier),
    providerObjectVersion: v.optional(v.number()),
    lastStripeObservedAt: v.optional(v.number()),
    version: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_businessId_and_currency', ['businessId', 'currency']).index('by_stripeAccountId', ['stripeAccountId']),
  moneyPayouts: defineTable({
    payoutRef: identifier,
    businessId: identifier,
    owningAccountRef: identifier,
    authorityPrincipalRef: identifier,
    authorityGrantRef: identifier,
    authorityGrantGeneration: v.number(),
    authorityResourceRefs: v.array(identifier),
    currency,
    exponent,
    grossAccrualUnits: units,
    rakeUnits: units,
    providerNetUnits: units,
    minimumPayoutUnits: units,
    cadence: v.literal('daily'),
    state: v.union(v.literal('review'), v.literal('held_kyc'), v.literal('held_threshold'), v.literal('transfer_pending'), v.literal('paid'), v.literal('reversed'), v.literal('failed'), v.literal('outcome_unknown')),
    periodStart: identifier,
    periodEnd: identifier,
    providerAccountRef: v.optional(identifier),
    destinationAccountId: v.optional(identifier),
    stripeTransferId: v.optional(identifier),
    payoutCommandId: v.optional(identifier),
    inputDigest: v.optional(identifier),
    transferRequestDigest: v.optional(identifier),
    transferEvidenceDigest: v.optional(identifier),
    transferReversalEvidenceDigest: v.optional(identifier),
    transferObservedAt: v.optional(v.number()),
    providerRecoveryDeadlineAt: v.optional(v.number()),
    transferStatus: v.optional(v.union(v.literal('pending'), v.literal('succeeded'), v.literal('failed'), v.literal('reversed'), v.literal('outcome_unknown'))),
    providerHeldBeforeUnits: v.optional(units),
    providerHeldAfterUnits: v.optional(units),
    providerPaidBeforeUnits: v.optional(units),
    providerPaidAfterUnits: v.optional(units),
    idempotencyKey: identifier,
    failureCode: v.optional(identifier),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_businessId_and_currency_and_state', ['businessId', 'currency', 'state'])
    .index('by_businessId_and_currency_and_state_and_updatedAt', ['businessId', 'currency', 'state', 'updatedAt'])
    .index('by_periodStart_and_state', ['periodStart', 'state'])
    .index('by_stripeTransferId', ['stripeTransferId'])
    .index('by_payoutRef', ['payoutRef'])
    .index('by_businessId_and_currency_and_updatedAt', ['businessId', 'currency', 'updatedAt'])
    .index('by_businessId_and_currency_and_cadence_and_updatedAt', ['businessId', 'currency', 'cadence', 'updatedAt']),
  moneyPayoutAllocations: defineTable({
    allocationRef: identifier,
    payoutRef: identifier,
    qualifiedUseRef: identifier,
    transactionRef: identifier,
    usageRef: identifier,
    businessId: identifier,
    owningAccountRef: identifier,
    authorityPrincipalRef: identifier,
    authorityGrantRef: identifier,
    authorityGrantGeneration: v.number(),
    authorityResourceRef: identifier,
    currency,
    exponent,
    grossAccrualUnits: units,
    rakeUnits: units,
    providerNetUnits: units,
    qualifiedAt: v.number(),
    sourceDigest: identifier,
    materialDigest: identifier,
    createdAt: v.number(),
  })
    .index('by_allocationRef', ['allocationRef'])
    .index('by_qualifiedUseRef', ['qualifiedUseRef'])
    .index('by_transactionRef', ['transactionRef'])
    .index('by_payoutRef_and_qualifiedAt', ['payoutRef', 'qualifiedAt'])
    .index('by_businessId_and_currency_and_qualifiedAt', [
      'businessId', 'currency', 'qualifiedAt',
    ]),
} as const
