
import { defineAction, type ActionParameter } from '@/modules/common/action'

import {
  createWorkTreeThroughSource,
  inspectWorkTreeThroughSource,
  workTreeCreateInputSchema,
  workTreeCreateResultSchema,
  workTreeInspectInputSchema,
  workTreeInspectResultSchema,
  type WorkTreeCreateInput,
  type WorkTreeCreateResult,
  type WorkTreeInspectInput,
  type WorkTreeInspectResult,
} from './work-tree.functions'

const guestAssertionParameter: ActionParameter = {
  name: 'guestAssertion',
  type: 'string',
  description: 'Opaque server-minted browser guest assertion; never a caller-chosen principal.',
  required: false,
}

const createParameters: readonly ActionParameter[] = [
  {
    name: 'idempotencyKey',
    type: 'string',
    description: 'Stable retry key for this project initialization request.',
    required: true,
  },
  {
    name: 'charterText',
    type: 'string',
    description: 'The outcome charter that names what this WorkTree is for.',
    required: true,
  },
  {
    name: 'lineage',
    type: 'object',
    description: 'Either the exact Customer Request revision or a standalone lineage.',
    required: true,
  },
  guestAssertionParameter,
]
const inspectParameters: readonly ActionParameter[] = [
  {
    name: 'projectId',
    type: 'string',
    description: 'Opaque project reference returned by workTree.create.',
    required: true,
  },
  guestAssertionParameter,
]

export const workTreeCreateAction = defineAction<WorkTreeCreateInput, WorkTreeCreateResult>({
  id: 'workTree.create',
  name: 'Create or resume a WorkTree',
  summary: 'Create one durable project WorkTree, or safely resume the exact existing tree for this principal and lineage.',
  boundaries: [
    'The project and WorkTree identities are generated by AE; callers cannot choose or reuse an identity from another principal.',
    'The principal comes from authenticated Clerk or agent source context, or from a verified server-minted browser guest assertion; callers never choose it.',
    'A repeated idempotency key with changed charter or lineage is refused without changing the tree.',
    'This creates source state and a root package only; it does not elaborate, decide, contact a business, charge, or claim fulfilment.',
    'Anonymous browser claim-cookie issuance and later claim rotation belong to the root host and are not performed by this action.',
  ],
  schema: workTreeCreateInputSchema,
  outputSchema: workTreeCreateResultSchema,
  parameters: createParameters,
  readOnly: false,
  effect: {
    class: 'external_state_change',
    reversible: false,
    recipientKind: 'none',
    dataClasses: ['work_tree'],
    spendExposure: 'none',
    approval: 'approve_each',
  },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.create:v1',
    consequenceClass: 'external_effect',
    materialInputPaths: ['idempotencyKey', 'charterText', 'lineage', 'guestAssertion'],
    authorityRequirement: 'principal',
    retryClass: 'attributable_retry',
    expectedEvidence: ['work_tree_creation_receipt', 'work_tree_readback'],
    safeContinuations: ['inspect the returned project reference before proposing work'],
    invalidationConditions: [
      'principal or authenticated source changes',
      'idempotency key is reused with a different charter or lineage',
      'Customer Request lineage revision changes',
      'action contract version changes',
    ],
  },
  run: async ({ data }) => createWorkTreeThroughSource(data),
})

export const workTreeInspectAction = defineAction<WorkTreeInspectInput, WorkTreeInspectResult>({
  id: 'workTree.inspect',
  name: 'Inspect a WorkTree',
  summary: 'Read the current source-owned WorkTree, capped event history and durable decision receipts for its authorized principal.',
  boundaries: [
    'Inspect-only; it never creates, mutates, elaborates, decides, contacts, charges, or dispatches.',
    'A different principal receives a typed refusal without a tree readback.',
    'The project reference is opaque and must come from a prior WorkTree source receipt.',
    'Anonymous MCP remains outside this private WorkTree surface.',
  ],
  schema: workTreeInspectInputSchema,
  outputSchema: workTreeInspectResultSchema,
  parameters: inspectParameters,
  readOnly: true,
  effect: {
    class: 'observation',
    reversible: true,
    recipientKind: 'none',
    dataClasses: ['work_tree', 'decision_receipts'],
    spendExposure: 'none',
    approval: 'none',
  },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.inspect:v1',
    consequenceClass: 'read_only',
    materialInputPaths: ['projectId', 'guestAssertion'],
    authorityRequirement: 'principal',
    retryClass: 'replayable',
    expectedEvidence: ['work_tree_readback'],
    safeContinuations: ['resume from the returned generation and revision fences'],
    invalidationConditions: [
      'principal changes',
      'project reference changes',
      'source snapshot or action contract version changes',
    ],
  },
  run: async ({ data }) => inspectWorkTreeThroughSource(data),
})

export type { WorkTreeCreateResult, WorkTreeInspectResult }
