import { defineAction } from '@/modules/common/action'

import {
  finalizeRepeatUseThroughSource,
  inspectRepeatUseThroughSource,
  reconcileRepeatUseThroughSource,
  reserveRepeatUseThroughSource,
  workTreeRepeatFinalizeResultSchema,
  workTreeRepeatInspectResultSchema,
  workTreeRepeatReconcileResultSchema,
  workTreeRepeatReserveResultSchema,
} from './work-tree-repeat.functions'
import {
  workTreeRepeatFinalizeInputSchema,
  workTreeRepeatInspectInputSchema,
  workTreeRepeatReconcileInputSchema,
  workTreeRepeatReserveInputSchema,
} from './internal/repeat-ledger'

export const workTreeReserveRepeatUseAction = defineAction({
  id: 'workTree.reserveRepeatUse',
  name: 'Reserve bounded WorkTree repeat use',
  summary: 'Reserve one exact bounded repeat use before any effect begins.',
  boundaries: [
    'The opaque permission reference is source-issued; callers cannot supply or widen authority fields.',
    'Reservation fences the WorkTree generation, revision, proposal and delegated credential stored with that permission.',
    'Occurrence, cumulative spend, and data caps are checked atomically; a refused reservation has no logical use.',
  ],
  schema: workTreeRepeatReserveInputSchema,
  outputSchema: workTreeRepeatReserveResultSchema,
  parameters: [
    { name: 'projectId', type: 'string', description: 'Owning WorkTree project.', required: true },
    { name: 'permissionRef', type: 'string', description: 'Opaque source-issued repeat permission reference.', required: true },
    { name: 'operationKey', type: 'string', description: 'Stable reservation retry identity.', required: true },
    { name: 'requestedOccurrences', type: 'number', description: 'Exact occurrence capacity to reserve.', required: true },
    { name: 'requestedSpend', type: 'object', description: 'Exact currency and maximum amount to reserve.', required: true },
    { name: 'requestedDataAllocations', type: 'number', description: 'Exact data allocation capacity to reserve.', required: true },
  ],
  readOnly: false,
  effect: { class: 'external_state_change', reversible: true, recipientKind: 'none', dataClasses: ['work_tree', 'authority'], spendExposure: 'bounded', approval: 'approve_each' },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.reserveRepeatUse:v1',
    consequenceClass: 'external_effect',
    materialInputPaths: ['projectId', 'permissionRef', 'operationKey', 'requestedOccurrences', 'requestedSpend', 'requestedDataAllocations'],
    authorityRequirement: 'principal',
    retryClass: 'attributable_retry',
    expectedEvidence: ['source reservation receipt with permission and WorkTree readback identity'],
    safeContinuations: ['finalize the reserved use or reconcile an unknown outcome'],
    invalidationConditions: ['permission status, credential, generation, revision or proposal changes', 'occurrence or cumulative spend cap is exhausted'],
  },
  run: async ({ data }) => reserveRepeatUseThroughSource(data),
})

export const workTreeFinalizeRepeatUseAction = defineAction({
  id: 'workTree.finalizeRepeatUse',
  name: 'Finalize WorkTree repeat use',
  summary: 'Record the observed repeat-use outcome and release unused reservation.',
  boundaries: [
    'A settled result records actual occurrence and spend and releases the unused reservation.',
    'An unknown result keeps the full reservation held until explicit reconciliation.',
    'Changed finalization payloads conflict; exact retries replay the same source receipt.',
    'This records source accounting and does not claim provider fulfilment or payment settlement.',
  ],
  schema: workTreeRepeatFinalizeInputSchema,
  outputSchema: workTreeRepeatFinalizeResultSchema,
  parameters: [
    { name: 'useRef', type: 'string', description: 'Opaque source reservation reference.', required: true },
    { name: 'operationKey', type: 'string', description: 'Stable finalization retry identity.', required: true },
    { name: 'actualOccurrences', type: 'number', description: 'Observed occurrences to settle.', required: true },
    { name: 'actualSpend', type: 'object', description: 'Observed spend when settled.', required: false },
    { name: 'actualDataAllocations', type: 'number', description: 'Observed data allocations when settled.', required: false },
    { name: 'outcome', type: 'string', description: 'Settled or outcome unknown.', required: true },
  ],
  readOnly: false,
  effect: { class: 'external_state_change', reversible: true, recipientKind: 'none', dataClasses: ['work_tree', 'authority'], spendExposure: 'bounded', approval: 'approve_each' },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.finalizeRepeatUse:v1',
    consequenceClass: 'external_effect',
    materialInputPaths: ['useRef', 'operationKey', 'actualOccurrences', 'actualSpend', 'actualDataAllocations', 'outcome'],
    authorityRequirement: 'principal',
    retryClass: 'reconcile_before_retry',
    expectedEvidence: ['source settlement receipt with released reservation amount'],
    safeContinuations: ['inspect the settled use; reconcile if outcome is unknown'],
    invalidationConditions: ['use is already finalized or the finalization payload changes'],
  },
  run: async ({ data }) => finalizeRepeatUseThroughSource(data),
})

export const workTreeReconcileRepeatUseAction = defineAction({
  id: 'workTree.reconcileRepeatUse',
  name: 'Reconcile unknown WorkTree repeat use',
  summary: 'Resolve one held unknown repeat use before another reservation.',
  boundaries: [
    'Only an unknown use can be reconciled; held capacity is not released by timeout or retry.',
    'The reconciliation evidence is part of the exact replay digest and changed payloads conflict.',
    'Reconciliation records source accounting only; it is not proof of external fulfilment.',
  ],
  schema: workTreeRepeatReconcileInputSchema,
  outputSchema: workTreeRepeatReconcileResultSchema,
  parameters: [
    { name: 'useRef', type: 'string', description: 'Opaque source reservation reference.', required: true },
    { name: 'operationKey', type: 'string', description: 'Stable reconciliation retry identity.', required: true },
    { name: 'actualOccurrences', type: 'number', description: 'Observed settled occurrences.', required: true },
    { name: 'actualSpend', type: 'object', description: 'Observed settled spend.', required: false },
    { name: 'actualDataAllocations', type: 'number', description: 'Observed settled data allocations.', required: false },
    { name: 'outcome', type: 'string', description: 'Settled or not settled.', required: true },
  ],
  readOnly: false,
  effect: { class: 'external_state_change', reversible: true, recipientKind: 'none', dataClasses: ['work_tree', 'authority'], spendExposure: 'bounded', approval: 'approve_each' },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.reconcileRepeatUse:v1',
    consequenceClass: 'external_effect',
    materialInputPaths: ['useRef', 'operationKey', 'actualOccurrences', 'actualSpend', 'actualDataAllocations', 'outcome'],
    authorityRequirement: 'principal',
    retryClass: 'attributable_retry',
    expectedEvidence: ['source reconciliation receipt and released reservation amount'],
    safeContinuations: ['inspect the reconciled use before a new reservation'],
    invalidationConditions: ['use is not unknown or reconciliation payload changes'],
  },
  run: async ({ data }) => reconcileRepeatUseThroughSource(data),
})

export const workTreeInspectRepeatUseAction = defineAction({
  id: 'workTree.inspectRepeatUse',
  name: 'Inspect WorkTree repeat use',
  summary: 'Read one bounded repeat-use reservation and its remaining permission capacity.',
  boundaries: [
    'Read-only; it does not reserve, settle or reconcile capacity.',
    'The readback is source accounting evidence, not provider fulfilment or payment evidence.',
  ],
  schema: workTreeRepeatInspectInputSchema,
  outputSchema: workTreeRepeatInspectResultSchema,
  parameters: [{ name: 'useRef', type: 'string', description: 'Opaque source reservation reference.', required: true }],
  readOnly: true,
  effect: { class: 'observation', reversible: true, recipientKind: 'none', dataClasses: ['work_tree', 'authority'], spendExposure: 'none', approval: 'none' },
  surfaces: ['ui', 'http', 'agentJson'],
  invocationContract: {
    version: 'workTree.inspectRepeatUse:v1',
    consequenceClass: 'read_only',
    materialInputPaths: ['useRef'],
    authorityRequirement: 'principal',
    retryClass: 'replayable',
    expectedEvidence: ['bounded source use and permission capacity readback'],
    safeContinuations: ['reconcile an unknown use before retrying'],
    invalidationConditions: ['use identity or owner changes'],
  },
  run: async ({ data }) => inspectRepeatUseThroughSource(data),
})
